// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class BPBOnlineTestCasesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
   // driver = new FirefoxDriver();
    System.setProperty("webdriver.chrome.driver",
            "C:\\Users\\rahma\\OneDrive\\Desktop\\Selenium\\chromedriver.exe");
    WebDriver driver;
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void bPBOnlineTestCases() {
    // Test name: BPB Online Test Cases
    // Step # | name | target | value | comment
    // 1 | open | https://bpbonline.com/ |  | 
    driver.get("https://bpbonline.com/");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | id=bc-product-search |  | 
    driver.findElement(By.id("bc-product-search")).click();
    // 4 | click | id=bc-product-search |  | 
    driver.findElement(By.id("bc-product-search")).click();
    // 5 | type | id=bc-product-search | selenium | 
    driver.findElement(By.id("bc-product-search")).sendKeys("selenium");
    // 6 | click | id=search |  | 
    driver.findElement(By.id("search")).click();
    // 7 | verifyTitle | Computer & IT Books | Emerging & Trending Technologies l E-books – BPB Publications |  | 
    assertThat(driver.getTitle(), is("Computer & IT Books | Emerging & Trending Technologies l E-books – BPB Publications"));
    // 8 | click | css=.tt-cursor .text-search-sn-search-shopify |  | 
    driver.findElement(By.cssSelector(".tt-cursor .text-search-sn-search-shopify")).click();
    // 9 | type | id=bc-product-search | C Under DOS Test by Riku Parikh, Anup Jalan, Soham Desai | 
    driver.findElement(By.id("bc-product-search")).sendKeys("C Under DOS Test by Riku Parikh, Anup Jalan, Soham Desai");
    // 10 | mouseOver | css=.active:nth-child(4) > .dropdown-link > span |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".active:nth-child(4) > .dropdown-link > span"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | assertText | css=span > strong | Description: | 
    assertThat(driver.findElement(By.cssSelector("span > strong")).getText(), is("Description:"));
    // 12 | click | css=.hover:nth-child(5) > a |  | 
    driver.findElement(By.cssSelector(".hover:nth-child(5) > a")).click();
    // 13 | click | id=bc-product-search |  | 
    driver.findElement(By.id("bc-product-search")).click();
    // 14 | click | css=.hover span |  | 
    driver.findElement(By.cssSelector(".hover span")).click();
    // 15 | click | id=bc-product-search |  | 
    driver.findElement(By.id("bc-product-search")).click();
    // 16 | type | id=bc-product-search | artif | 
    driver.findElement(By.id("bc-product-search")).sendKeys("artif");
    // 17 | click | id=bc-product-search |  | 
    driver.findElement(By.id("bc-product-search")).click();
    // 18 | assertText | css=.tt-cursor .content-lineal-sn-search-shopify | Artificial Intelligence | 
    assertThat(driver.findElement(By.cssSelector(".tt-cursor .content-lineal-sn-search-shopify")).getText(), is("Artificial Intelligence"));
    // 19 | click | css=.tt-cursor .tt-highlight |  | 
    driver.findElement(By.cssSelector(".tt-cursor .tt-highlight")).click();
    // 20 | type | id=bc-product-search | Artificial Intelligence | 
    driver.findElement(By.id("bc-product-search")).sendKeys("Artificial Intelligence");
    // 21 | click | css=.grid |  | 
    driver.findElement(By.cssSelector(".grid")).click();
    // 22 | mouseOver | css=.product-grid-item:nth-child(2) .featured-image |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-grid-item:nth-child(2) .featured-image"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | click | css=.product-grid-item:nth-child(2) .featured-image |  | 
    driver.findElement(By.cssSelector(".product-grid-item:nth-child(2) .featured-image")).click();
    // 24 | storeTitle | AI & ML - Powering the Agents of Automation – BPB Publications | AIBook | 
    vars.put("AIBook", driver.getTitle());
    // 25 | click | id=add-to-cart |  | 
    driver.findElement(By.id("add-to-cart")).click();
    // 26 | click | css=.action > .btn-default |  | 
    driver.findElement(By.cssSelector(".action > .btn-default")).click();
    // 27 | mouseDownAt | id=checkout_email_or_phone | 407.15625,24.015625 | 
    {
      WebElement element = driver.findElement(By.id("checkout_email_or_phone"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 28 | mouseMoveAt | id=checkout_email_or_phone | 407.15625,24.015625 | 
    {
      WebElement element = driver.findElement(By.id("checkout_email_or_phone"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 29 | mouseUpAt | id=checkout_email_or_phone | 407.15625,24.015625 | 
    {
      WebElement element = driver.findElement(By.id("checkout_email_or_phone"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 30 | click | id=checkout_email_or_phone |  | 
    driver.findElement(By.id("checkout_email_or_phone")).click();
    // 31 | type | id=checkout_email_or_phone | abc@def.com | 
    driver.findElement(By.id("checkout_email_or_phone")).sendKeys("abc@def.com");
    // 32 | type | name=checkout[shipping_address][first_name] | Selenium | 
    driver.findElement(By.name("checkout[shipping_address][first_name]")).sendKeys("Selenium");
    // 33 | type | name=checkout[shipping_address][last_name] | User | 
    driver.findElement(By.name("checkout[shipping_address][last_name]")).sendKeys("User");
    // 34 | type | name=checkout[shipping_address][address1] | 12345, Sixth Street | 
    driver.findElement(By.name("checkout[shipping_address][address1]")).sendKeys("12345, Sixth Street");
    // 35 | type | name=checkout[shipping_address][address2] | Seventh Avenue | 
    driver.findElement(By.name("checkout[shipping_address][address2]")).sendKeys("Seventh Avenue");
    // 36 | type | name=checkout[shipping_address][city] | Denver | 
    driver.findElement(By.name("checkout[shipping_address][city]")).sendKeys("Denver");
    // 37 | type | name=checkout[shipping_address][country] | US | 
    driver.findElement(By.name("checkout[shipping_address][country]")).sendKeys("US");
    // 38 | type | name=checkout[shipping_address][province] | Colorado | 
    driver.findElement(By.name("checkout[shipping_address][province]")).sendKeys("Colorado");
    // 39 | type | name=checkout[shipping_address][zip] | 80201 | 
    driver.findElement(By.name("checkout[shipping_address][zip]")).sendKeys("80201");
    // 40 | type | name=checkout[shipping_address][phone] | 9876543241 | 
    driver.findElement(By.name("checkout[shipping_address][phone]")).sendKeys("9876543241");
    // 41 | click | id=checkout_remember_me |  | 
    driver.findElement(By.id("checkout_remember_me")).click();
    // 42 | click | css=.icon-svg--size-18 |  | 
    driver.findElement(By.cssSelector(".icon-svg--size-18")).click();
    // 43 | click | css=.btn__content |  | 
    driver.findElement(By.cssSelector(".btn__content")).click();
    // 44 | click | css=.radio-wrapper:nth-child(2) > .radio__label |  | 
    driver.findElement(By.cssSelector(".radio-wrapper:nth-child(2) > .radio__label")).click();
    // 45 | click | css=.shown-if-js > #continue_button > .icon-svg |  | 
    driver.findElement(By.cssSelector(".shown-if-js > #continue_button > .icon-svg")).click();
    // 46 | selectFrame | index=0 |  | 
    driver.switchTo().frame(0);
    // 47 | assertTitle | Razorpay Checkout |  | 
    assertThat(driver.getTitle(), is("Razorpay Checkout"));
    // 48 | close |  |  | 
    driver.close();
  }
}
