// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class DemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
            "C:\\Users\\rahma\\OneDrive\\Desktop\\Selenium\\chromedriver.exe");
    WebDriver driver;
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() {
    // Test name: demo
    // Step # | name | target | value | comment
    // 1 | open | Demo website at Applitools |  |
    driver.get("https://demo.applitools.com/");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | verifyText | css=.auth-header | Check CSS Selector to check if the section header says Login Form |
    assertThat(driver.findElement(By.cssSelector(".auth-header")).getText(), is("Login Form"));
    // 4 | click on | id=username |  |
    driver.findElement(By.id("username")).click();
    // 5 | type user name| id=username | demo |
    driver.findElement(By.id("username")).sendKeys("demo");
    // 6 | type type password| id=password | demo |
    driver.findElement(By.id("password")).sendKeys("demo");
    // 7 | click Log in button| id=log-in |  |
    driver.findElement(By.id("log-in")).click();
    // 8 | assertTitle | ACME demo app |  | 
    assertThat(driver.getTitle(), is("ACME demo app"));
    // 9 | Print Page Content |  |  |
    String content = webDriver.findElement(By.tagName("body")).getText();
    System.out.println(content);
    // 10 | close |  |  |
    print(driver.page_source)

    driver.close();
  }
}
