// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class DemoNewToursTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //driver = new FirefoxDriver();
    System.setProperty("webdriver.chrome.driver",
            "C:\\Users\\rahma\\OneDrive\\Desktop\\Selenium\\chromedriver.exe");
    WebDriver driver;
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void demoNewTours() {
    // Test name: DemoNewTours
    // Step # | name | target | value | comment
    // 1 | open | http://newtours.demoaut.com/ |  | 
    driver.get("http://newtours.demoaut.com/");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | linkText=REGISTER |  | 
    driver.findElement(By.linkText("REGISTER")).click();
    // 4 | click | css=form tr:nth-child(1) > td |  | 
    driver.findElement(By.cssSelector("form tr:nth-child(1) > td")).click();
    // 5 | click | name=firstName |  | 
    driver.findElement(By.name("firstName")).click();
    // 6 | type | name=firstName | Selenium | 
    driver.findElement(By.name("firstName")).sendKeys("Selenium");
    // 7 | type | name=lastName | User | 
    driver.findElement(By.name("lastName")).sendKeys("User");
    // 8 | type | name=phone | 987-654-3241 | 
    driver.findElement(By.name("phone")).sendKeys("987-654-3241");
    // 9 | type | id=userName | abc@def.com | 
    driver.findElement(By.id("userName")).sendKeys("abc@def.com");
    // 10 | type | name=address1 | 12345, Sixth Street | 
    driver.findElement(By.name("address1")).sendKeys("12345, Sixth Street");
    // 11 | type | name=address2 | Seventh Avenue | 
    driver.findElement(By.name("address2")).sendKeys("Seventh Avenue");
    // 12 | type | name=city | Denver | 
    driver.findElement(By.name("city")).sendKeys("Denver");
    // 13 | type | name=state | Colorado | 
    driver.findElement(By.name("state")).sendKeys("Colorado");
    // 14 | type | name=postalCode | 80201 | 
    driver.findElement(By.name("postalCode")).sendKeys("80201");
    // 15 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 16 | type | id=email | selenium_tester1 | 
    driver.findElement(By.id("email")).sendKeys("selenium_tester1");
    // 17 | type | name=password | password | 
    driver.findElement(By.name("password")).sendKeys("password");
    // 18 | type | name=confirmPassword | password | 
    driver.findElement(By.name("confirmPassword")).sendKeys("password");
    // 19 | click | name=register |  | 
    driver.findElement(By.name("register")).click();
    // 20 | click | linkText=Home |  | 
    driver.findElement(By.linkText("Home")).click();
    // 21 | click | name=login |  | 
    driver.findElement(By.name("login")).click();
    // 22 | click | name=fromPort |  | 
    driver.findElement(By.name("fromPort")).click();
    // 23 | select | name=fromPort | label=Sydney | 
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Sydney']")).click();
    }
    // 24 | click | name=fromPort |  | 
    driver.findElement(By.name("fromPort")).click();
    // 25 | click | name=toPort |  | 
    driver.findElement(By.name("toPort")).click();
    // 26 | select | name=toPort | label=New York | 
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'New York']")).click();
    }
    // 27 | click | name=toPort |  | 
    driver.findElement(By.name("toPort")).click();
    // 28 | click | css=input:nth-child(4) |  | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    // 29 | click | name=airline |  | 
    driver.findElement(By.name("airline")).click();
    // 30 | select | name=airline | label=Unified Airlines | 
    {
      WebElement dropdown = driver.findElement(By.name("airline"));
      dropdown.findElement(By.xpath("//option[. = 'Unified Airlines']")).click();
    }
    // 31 | click | name=airline |  | 
    driver.findElement(By.name("airline")).click();
    // 32 | click | name=findFlights |  | 
    driver.findElement(By.name("findFlights")).click();
    // 33 | click | css=table:nth-child(9) tr:nth-child(9) input |  | 
    driver.findElement(By.cssSelector("table:nth-child(9) tr:nth-child(9) input")).click();
    // 34 | click | css=table:nth-child(10) tr:nth-child(9) > .frame_action_xrows |  | 
    driver.findElement(By.cssSelector("table:nth-child(10) tr:nth-child(9) > .frame_action_xrows")).click();
    // 35 | click | css=table:nth-child(10) tr:nth-child(9) input |  | 
    driver.findElement(By.cssSelector("table:nth-child(10) tr:nth-child(9) input")).click();
    // 36 | click | name=reserveFlights |  | 
    driver.findElement(By.name("reserveFlights")).click();
    // 37 | click | css=table:nth-child(20) > tbody > tr:nth-child(4) > td |  | 
    driver.findElement(By.cssSelector("table:nth-child(20) > tbody > tr:nth-child(4) > td")).click();
    // 38 | click | name=passFirst0 |  | 
    driver.findElement(By.name("passFirst0")).click();
    // 39 | click | name=passFirst0 |  | 
    driver.findElement(By.name("passFirst0")).click();
    // 40 | doubleClick | name=passFirst0 |  | 
    {
      WebElement element = driver.findElement(By.name("passFirst0"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 41 | click | css=table:nth-child(20) tr:nth-child(4) tr:nth-child(1) > td:nth-child(1) |  | 
    driver.findElement(By.cssSelector("table:nth-child(20) tr:nth-child(4) tr:nth-child(1) > td:nth-child(1)")).click();
    // 42 | click | name=passFirst0 |  | 
    driver.findElement(By.name("passFirst0")).click();
    // 43 | type | name=passFirst0 | Traveller | 
    driver.findElement(By.name("passFirst0")).sendKeys("Traveller");
    // 44 | type | name=passLast0 | Tester | 
    driver.findElement(By.name("passLast0")).sendKeys("Tester");
    // 45 | click | css=tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td:nth-child(3)")).click();
    // 46 | click | name=pass.0.meal |  | 
    driver.findElement(By.name("pass.0.meal")).click();
    // 47 | select | name=pass.0.meal | label=Vegetarian | 
    {
      WebElement dropdown = driver.findElement(By.name("pass.0.meal"));
      dropdown.findElement(By.xpath("//option[. = 'Vegetarian']")).click();
    }
    // 48 | click | name=pass.0.meal |  | 
    driver.findElement(By.name("pass.0.meal")).click();
    // 49 | click | name=creditCard |  | 
    driver.findElement(By.name("creditCard")).click();
    // 50 | select | name=creditCard | label=Visa | 
    {
      WebElement dropdown = driver.findElement(By.name("creditCard"));
      dropdown.findElement(By.xpath("//option[. = 'Visa']")).click();
    }
    // 51 | click | name=creditCard |  | 
    driver.findElement(By.name("creditCard")).click();
    // 52 | click | css=tr:nth-child(7) tr:nth-child(2) > td:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(7) tr:nth-child(2) > td:nth-child(2)")).click();
    // 53 | type | name=creditnumber | 1234567890123456 | 
    driver.findElement(By.name("creditnumber")).sendKeys("1234567890123456");
    // 54 | click | name=cc_exp_dt_mn |  | 
    driver.findElement(By.name("cc_exp_dt_mn")).click();
    // 55 | select | name=cc_exp_dt_mn | label=11 | 
    {
      WebElement dropdown = driver.findElement(By.name("cc_exp_dt_mn"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    // 56 | click | name=cc_exp_dt_mn |  | 
    driver.findElement(By.name("cc_exp_dt_mn")).click();
    // 57 | click | name=cc_exp_dt_yr |  | 
    driver.findElement(By.name("cc_exp_dt_yr")).click();
    // 58 | select | name=cc_exp_dt_yr | label=2010 | 
    {
      WebElement dropdown = driver.findElement(By.name("cc_exp_dt_yr"));
      dropdown.findElement(By.xpath("//option[. = '2010']")).click();
    }
    // 59 | click | name=cc_exp_dt_yr |  | 
    driver.findElement(By.name("cc_exp_dt_yr")).click();
    // 60 | click | name=cc_frst_name |  | 
    driver.findElement(By.name("cc_frst_name")).click();
    // 61 | click | css=tr:nth-child(8) tr:nth-child(1) > td:nth-child(1) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(8) tr:nth-child(1) > td:nth-child(1)")).click();
    // 62 | click | name=passFirst0 |  | 
    driver.findElement(By.name("passFirst0")).click();
    // 63 | click | name=passFirst0 |  | 
    driver.findElement(By.name("passFirst0")).click();
    // 64 | doubleClick | name=passFirst0 |  | 
    {
      WebElement element = driver.findElement(By.name("passFirst0"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 65 | click | css=tr:nth-child(8) tbody |  | 
    driver.findElement(By.cssSelector("tr:nth-child(8) tbody")).click();
    // 66 | click | name=cc_frst_name |  | 
    driver.findElement(By.name("cc_frst_name")).click();
    // 67 | type | name=cc_frst_name | Traveller | 
    driver.findElement(By.name("cc_frst_name")).sendKeys("Traveller");
    // 68 | click | name=passLast0 |  | 
    driver.findElement(By.name("passLast0")).click();
    // 69 | click | name=passLast0 |  | 
    driver.findElement(By.name("passLast0")).click();
    // 70 | doubleClick | name=passLast0 |  | 
    {
      WebElement element = driver.findElement(By.name("passLast0"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 71 | click | name=cc_last_name |  | 
    driver.findElement(By.name("cc_last_name")).click();
    // 72 | type | name=cc_last_name | Tester | 
    driver.findElement(By.name("cc_last_name")).sendKeys("Tester");
    // 73 | click | name=cc_mid_name |  | 
    driver.findElement(By.name("cc_mid_name")).click();
    // 74 | click | css=tr:nth-child(15) input |  | 
    driver.findElement(By.cssSelector("tr:nth-child(15) input")).click();
    // 75 | click | name=ticketLess |  | 
    driver.findElement(By.name("ticketLess")).click();
    // 76 | click | name=buyFlights |  | 
    driver.findElement(By.name("buyFlights")).click();
    // 77 | click | css=font > img |  | 
    driver.findElement(By.cssSelector("font > img")).click();
    // 78 | click | css=font > img |  | 
    driver.findElement(By.cssSelector("font > img")).click();
    // 79 | click | css=td:nth-child(1) > a > img |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) > a > img")).click();
    // 80 | click | linkText=Flights |  | 
    driver.findElement(By.linkText("Flights")).click();
    // 81 | click | linkText=Hotels |  | 
    driver.findElement(By.linkText("Hotels")).click();
    // 82 | click | css=a > img |  | 
    driver.findElement(By.cssSelector("a > img")).click();
    // 83 | click | linkText=Car Rentals |  | 
    driver.findElement(By.linkText("Car Rentals")).click();
    // 84 | click | linkText=Cruises |  | 
    driver.findElement(By.linkText("Cruises")).click();
    // 85 | click | css=td:nth-child(1) td:nth-child(1) > img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(1) > img:nth-child(1)")).click();
    // 86 | click | linkText=Destinations |  | 
    driver.findElement(By.linkText("Destinations")).click();
    // 87 | click | linkText=Vacations |  | 
    driver.findElement(By.linkText("Vacations")).click();
    // 88 | click | linkText=Home |  | 
    driver.findElement(By.linkText("Home")).click();
    // 89 | click | linkText=Flights |  | 
    driver.findElement(By.linkText("Flights")).click();
    // 90 | click | name=login |  | 
    driver.findElement(By.name("login")).click();
    // 91 | click | linkText=ITINERARY |  | 
    driver.findElement(By.linkText("ITINERARY")).click();
    // 92 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 93 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 94 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 95 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 96 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 97 | click | css=.\_hsShareImage |  | 
    driver.findElement(By.cssSelector(".\_hsShareImage")).click();
    // 98 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 99 | storeWindowHandle | root |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 100 | selectWindow | handle=${win5947} |  | 
    vars.put("win5947", waitForWindow(2000));
    // 101 | close |  |  | 
    vars.put("root", driver.getWindowHandle());
    // 102 | selectWindow | handle=${root} |  | 
    driver.switchTo().window(vars.get("win5947").toString());
    // 103 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    driver.close();
    // 104 | mouseDownAt | css=area | 345,-82 | 
    driver.switchTo().window(vars.get("root").toString());
    // 105 | mouseMoveAt | css=area | 345,-82 | 
    driver.findElement(By.cssSelector("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click();
    // 106 | mouseUpAt | css=area | 345,-82 | 
    {
      WebElement element = driver.findElement(By.cssSelector("area"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 107 | click | css=area |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("area"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 108 | mouseDownAt | css=area | 352,-82 | 
    {
      WebElement element = driver.findElement(By.cssSelector("area"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 109 | mouseMoveAt | css=area | 352,-82 | 
    driver.findElement(By.cssSelector("area")).click();
    // 110 | mouseUpAt | css=area | 352,-82 | 
    {
      WebElement element = driver.findElement(By.cssSelector("area"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 111 | click | css=area |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("area"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 112 | type | name=userName | selenium_tester1 | 
    {
      WebElement element = driver.findElement(By.cssSelector("area"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 113 | type | name=password | password | 
    driver.findElement(By.cssSelector("area")).click();
    // 114 | click | name=login |  | 
    driver.findElement(By.name("userName")).sendKeys("selenium_tester1");
    // 115 | click | name=toPort |  | 
    driver.findElement(By.name("password")).sendKeys("password");
    // 116 | select | name=toPort | label=Sydney | 
    driver.findElement(By.name("login")).click();
    // 117 | click | name=toPort |  | 
    driver.findElement(By.name("toPort")).click();
    // 118 | click | name=toDay |  | 
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'Sydney']")).click();
    }
    // 119 | click | name=toMonth |  | 
    driver.findElement(By.name("toPort")).click();
    // 120 | select | name=toMonth | label=November | 
    driver.findElement(By.name("toDay")).click();
    // 121 | click | name=toMonth |  | 
    driver.findElement(By.name("toMonth")).click();
    // 122 | click | name=airline |  | 
    {
      WebElement dropdown = driver.findElement(By.name("toMonth"));
      dropdown.findElement(By.xpath("//option[. = 'November']")).click();
    }
    // 123 | click | css=tr:nth-child(9) > td:nth-child(2) |  | 
    driver.findElement(By.name("toMonth")).click();
    // 124 | click | name=findFlights |  | 
    driver.findElement(By.name("airline")).click();
    // 125 | click | css=table:nth-child(10) tr:nth-child(7) > .frame_action_xrows |  | 
    driver.findElement(By.cssSelector("tr:nth-child(9) > td:nth-child(2)")).click();
    // 126 | click | css=table:nth-child(10) tr:nth-child(7) input |  | 
    driver.findElement(By.name("findFlights")).click();
    // 127 | click | name=reserveFlights |  | 
    driver.findElement(By.cssSelector("table:nth-child(10) tr:nth-child(7) > .frame_action_xrows")).click();
    // 128 | type | name=passFirst0 | Selenium | 
    driver.findElement(By.cssSelector("table:nth-child(10) tr:nth-child(7) input")).click();
    // 129 | type | name=passLast0 | User | 
    driver.findElement(By.name("reserveFlights")).click();
    // 130 | click | name=cc_frst_name |  | 
    driver.findElement(By.name("passFirst0")).sendKeys("Selenium");
    // 131 | click | name=cc_frst_name |  | 
    driver.findElement(By.name("passLast0")).sendKeys("User");
    // 132 | doubleClick | name=cc_frst_name |  | 
    driver.findElement(By.name("cc_frst_name")).click();
    // 133 | type | name=cc_frst_name | Selenium | 
    driver.findElement(By.name("cc_frst_name")).click();
    // 134 | type | name=cc_last_name | User | 
    {
      WebElement element = driver.findElement(By.name("cc_frst_name"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 135 | type | name=billAddress2 | Seventh Avenue | 
    driver.findElement(By.name("cc_frst_name")).sendKeys("Selenium");
    // 136 | click | name=creditCard |  | 
    driver.findElement(By.name("cc_last_name")).sendKeys("User");
    // 137 | select | name=creditCard | label=Visa | 
    driver.findElement(By.name("billAddress2")).sendKeys("Seventh Avenue");
    // 138 | click | name=creditCard |  | 
    driver.findElement(By.name("creditCard")).click();
    // 139 | click | css=table:nth-child(20) > tbody > tr:nth-child(9) > td:nth-child(1) |  | 
    {
      WebElement dropdown = driver.findElement(By.name("creditCard"));
      dropdown.findElement(By.xpath("//option[. = 'Visa']")).click();
    }
    // 140 | click | name=creditnumber |  | 
    driver.findElement(By.name("creditCard")).click();
    // 141 | type | name=creditnumber | 1234567890123456 | 
    driver.findElement(By.cssSelector("table:nth-child(20) > tbody > tr:nth-child(9) > td:nth-child(1)")).click();
    // 142 | click | name=cc_exp_dt_mn |  | 
    driver.findElement(By.name("creditnumber")).click();
    // 143 | select | name=cc_exp_dt_mn | label=11 | 
    driver.findElement(By.name("creditnumber")).sendKeys("1234567890123456");
    // 144 | click | name=cc_exp_dt_mn |  | 
    driver.findElement(By.name("cc_exp_dt_mn")).click();
    // 145 | click | css=tr:nth-child(7) tr:nth-child(2) > td:nth-child(3) |  | 
    {
      WebElement dropdown = driver.findElement(By.name("cc_exp_dt_mn"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    // 146 | click | name=cc_exp_dt_yr |  | 
    driver.findElement(By.name("cc_exp_dt_mn")).click();
    // 147 | select | name=cc_exp_dt_yr | label=2010 | 
    driver.findElement(By.cssSelector("tr:nth-child(7) tr:nth-child(2) > td:nth-child(3)")).click();
    // 148 | click | name=cc_exp_dt_yr |  | 
    driver.findElement(By.name("cc_exp_dt_yr")).click();
    // 149 | click | css=body > div |  | 
    {
      WebElement dropdown = driver.findElement(By.name("cc_exp_dt_yr"));
      dropdown.findElement(By.xpath("//option[. = '2010']")).click();
    }
    // 150 | click | name=ticketLess |  | 
    driver.findElement(By.name("cc_exp_dt_yr")).click();
    // 151 | click | css=tr:nth-child(15) input |  | 
    driver.findElement(By.cssSelector("body > div")).click();
    // 152 | click | name=buyFlights |  | 
    driver.findElement(By.name("ticketLess")).click();
    // 153 | click | css=font > img |  | 
    driver.findElement(By.cssSelector("tr:nth-child(15) input")).click();
    // 154 | click | css=font > img |  | 
    driver.findElement(By.name("buyFlights")).click();
    // 155 | doubleClick | css=font > img |  | 
    driver.findElement(By.cssSelector("font > img")).click();
    // 156 | click | css=td:nth-child(1) tr:nth-child(1) > td:nth-child(1) > img:nth-child(1) |  | 
    driver.findElement(By.cssSelector("font > img")).click();
    // 157 | click | css=td:nth-child(2) > a > img |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("font > img"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 158 | click | linkText=SUPPORT |  | 
    driver.findElement(By.cssSelector("td:nth-child(1) tr:nth-child(1) > td:nth-child(1) > img:nth-child(1)")).click();
    // 159 | click | css=a > img |  | 
    driver.findElement(By.cssSelector("td:nth-child(2) > a > img")).click();
    // 160 | click | linkText=CONTACT |  | 
    driver.findElement(By.linkText("SUPPORT")).click();
    // 161 | click | css=a > img |  | 
    driver.findElement(By.cssSelector("a > img")).click();
    // 162 | click | css=p:nth-child(4) > img |  | 
    driver.findElement(By.linkText("CONTACT")).click();
    // 163 | click | css=table:nth-child(3) tr:nth-child(3) img |  | 
    driver.findElement(By.cssSelector("a > img")).click();
    // 164 | click | css=tr:nth-child(10) img |  | 
    driver.findElement(By.cssSelector("p:nth-child(4) > img")).click();
    // 165 | click | css=a:nth-child(2) |  | 
    driver.findElement(By.cssSelector("table:nth-child(3) tr:nth-child(3) img")).click();
    // 166 | selectWindow | handle=${win37} |  | 
    driver.findElement(By.cssSelector("tr:nth-child(10) img")).click();
    // 167 | close |  |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 168 | selectWindow | handle=${root} |  | 
    driver.findElement(By.cssSelector("a:nth-child(2)")).click();
    // 169 | click | linkText=featured vacation destinations |  | 
    vars.put("win37", waitForWindow(2000));
    driver.switchTo().window(vars.get("win37").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("featured vacation destinations")).click();
  }
}
