// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class TheautomatedtestertestcasesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void theautomatedtestertestcases() {
    // Test name: theautomatedtestertestcases
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://book.theautomatedtester.co.uk/");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | linkText=Chapter1 |  | 
    driver.findElement(By.linkText("Chapter1")).click();
    // 4 | click | id=verifybutton |  | 
    driver.findElement(By.id("verifybutton")).click();
    // 5 | click | id=verifybutton |  | 
    driver.findElement(By.id("verifybutton")).click();
    // 6 | click | id=multiplewindow |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 7 | storeWindowHandle | root |  | 
    driver.findElement(By.id("multiplewindow")).click();
    // 8 | selectWindow | handle=${win386} |  | 
    vars.put("win386", waitForWindow(2000));
    // 9 | click | id=closepopup |  | 
    vars.put("root", driver.getWindowHandle());
    // 10 | close |  |  | 
    driver.switchTo().window(vars.get("win386").toString());
    // 11 | selectWindow | handle=${root} |  | 
    driver.findElement(By.id("closepopup")).click();
    // 12 | click | xpath=(//div[@id='multiplewindow'])[2] |  | 
    driver.close();
    // 13 | selectWindow | handle=${win893} |  | 
    driver.switchTo().window(vars.get("root").toString());
    // 14 | click | id=closepopup |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 15 | close |  |  | 
    driver.findElement(By.xpath("(//div[@id=\'multiplewindow\'])[2]")).click();
    // 16 | selectWindow | handle=${root} |  | 
    vars.put("win893", waitForWindow(2000));
    // 17 | mouseDownAt | id=divontheleft | 15,1 | 
    driver.switchTo().window(vars.get("win893").toString());
    // 18 | mouseMoveAt | id=divontheleft | 15,1 | 
    driver.findElement(By.id("closepopup")).click();
    // 19 | mouseUpAt | id=divontheleft | 15,1 | 
    driver.close();
    // 20 | click | id=divontheleft |  | 
    driver.switchTo().window(vars.get("root").toString());
    // 21 | mouseDownAt | id=divontheleft | 138,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 22 | mouseMoveAt | id=divontheleft | 138,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | mouseUpAt | id=divontheleft | 138,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 24 | click | id=divontheleft |  | 
    driver.findElement(By.id("divontheleft")).click();
    // 25 | click | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 26 | doubleClick | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 27 | doubleClick | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 28 | doubleClick | id=divontheleft |  | 
    driver.findElement(By.id("divontheleft")).click();
    // 29 | mouseDownAt | id=divontheleft | 97,7 | 
    driver.findElement(By.id("divontheleft")).click();
    // 30 | mouseMoveAt | id=divontheleft | 97,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 31 | mouseUpAt | id=divontheleft | 97,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 32 | click | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 33 | mouseDownAt | id=divontheleft | 96,6 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 34 | mouseMoveAt | id=divontheleft | 96,6 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 35 | mouseUpAt | id=divontheleft | 96,6 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 36 | click | id=divontheleft |  | 
    driver.findElement(By.id("divontheleft")).click();
    // 37 | doubleClick | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 38 | doubleClick | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 39 | doubleClick | id=divontheleft |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 40 | mouseDownAt | id=loadajax | 91,7 | 
    driver.findElement(By.id("divontheleft")).click();
    // 41 | mouseMoveAt | id=loadajax | 91,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 42 | mouseUpAt | id=loadajax | 91,7 | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 43 | click | id=loadajax |  | 
    {
      WebElement element = driver.findElement(By.id("divontheleft"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 44 | mouseDownAt | css=#ajaxdiv > p | 108,26 | 
    {
      WebElement element = driver.findElement(By.id("loadajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 45 | mouseMoveAt | css=#ajaxdiv > p | 108,26 | 
    {
      WebElement element = driver.findElement(By.id("loadajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 46 | mouseUpAt | css=#ajaxdiv > p | 108,26 | 
    {
      WebElement element = driver.findElement(By.id("loadajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 47 | click | css=#ajaxdiv > p |  | 
    driver.findElement(By.id("loadajax")).click();
    // 48 | mouseDownAt | id=loadajax | 6,7 | 
    {
      WebElement element = driver.findElement(By.cssSelector("#ajaxdiv > p"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 49 | mouseMoveAt | id=loadajax | 6,7 | 
    {
      WebElement element = driver.findElement(By.cssSelector("#ajaxdiv > p"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 50 | mouseUpAt | id=loadajax | 6,7 | 
    {
      WebElement element = driver.findElement(By.cssSelector("#ajaxdiv > p"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 51 | click | id=loadajax |  | 
    driver.findElement(By.cssSelector("#ajaxdiv > p")).click();
    // 52 | mouseDownAt | id=secondajax | 240,18 | 
    {
      WebElement element = driver.findElement(By.id("loadajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 53 | mouseMoveAt | id=secondajax | 240,18 | 
    {
      WebElement element = driver.findElement(By.id("loadajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 54 | mouseUpAt | id=secondajax | 240,18 | 
    {
      WebElement element = driver.findElement(By.id("loadajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 55 | click | id=secondajax |  | 
    driver.findElement(By.id("loadajax")).click();
    // 56 | mouseDownAt | id=secondajax | 241,15 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 57 | mouseMoveAt | id=secondajax | 241,15 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 58 | mouseUpAt | id=secondajax | 241,15 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 59 | click | id=secondajax |  | 
    driver.findElement(By.id("secondajax")).click();
    // 60 | doubleClick | id=secondajax |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 61 | doubleClick | id=secondajax |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 62 | doubleClick | id=secondajax |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 63 | mouseDownAt | id=secondajaxbutton | 97,5 | 
    driver.findElement(By.id("secondajax")).click();
    // 64 | mouseMoveAt | id=secondajaxbutton | 97,5 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 65 | mouseUpAt | id=secondajaxbutton | 97,5 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 66 | click | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 67 | mouseDownAt | id=secondajaxbutton | 100,8 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 68 | mouseMoveAt | id=secondajaxbutton | 100,8 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 69 | mouseUpAt | id=secondajaxbutton | 100,8 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 70 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 71 | mouseDownAt | id=secondajaxbutton | 122,15 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 72 | mouseMoveAt | id=secondajaxbutton | 122,15 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 73 | mouseUpAt | id=secondajaxbutton | 122,15 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 74 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 75 | mouseDownAt | id=secondajaxbutton | 121,14 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 76 | mouseMoveAt | id=secondajaxbutton | 121,14 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 77 | mouseUpAt | id=secondajaxbutton | 121,14 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 78 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 79 | doubleClick | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 80 | doubleClick | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 81 | doubleClick | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 82 | mouseDownAt | id=secondajaxbutton | 121,12 | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 83 | mouseMoveAt | id=secondajaxbutton | 121,12 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 84 | mouseUpAt | id=secondajaxbutton | 121,12 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 85 | click | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 86 | mouseDownAt | id=secondajaxbutton | 121,12 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 87 | mouseMoveAt | id=secondajaxbutton | 121,12 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 88 | mouseUpAt | id=secondajaxbutton | 121,12 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 89 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 90 | mouseDownAt | id=secondajaxbutton | 87,4 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 91 | mouseMoveAt | id=secondajaxbutton | 87,4 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 92 | mouseUpAt | id=secondajaxbutton | 87,4 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 93 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 94 | mouseDownAt | id=secondajaxbutton | 84,3 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 95 | mouseMoveAt | id=secondajaxbutton | 84,3 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 96 | mouseUpAt | id=secondajaxbutton | 84,3 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 97 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 98 | mouseDownAt | id=secondajaxbutton | 83,3 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 99 | mouseMoveAt | id=secondajaxbutton | 83,3 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 100 | mouseUpAt | id=secondajaxbutton | 83,3 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 101 | click | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 102 | click | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 103 | doubleClick | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 104 | doubleClick | id=secondajaxbutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 105 | doubleClick | id=secondajaxbutton |  | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 106 | mouseDownAt | id=verifybutton | 23.5,13.5 | 
    driver.findElement(By.id("secondajaxbutton")).click();
    // 107 | mouseMoveAt | id=verifybutton | 23.5,13.5 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 108 | mouseUpAt | id=verifybutton | 23.5,13.5 | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 109 | click | id=verifybutton |  | 
    {
      WebElement element = driver.findElement(By.id("secondajaxbutton"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 110 | mouseDownAt | id=storeinput | 99,14 | 
    {
      WebElement element = driver.findElement(By.id("verifybutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 111 | mouseMoveAt | id=storeinput | 99,14 | 
    {
      WebElement element = driver.findElement(By.id("verifybutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 112 | mouseUpAt | id=storeinput | 99,14 | 
    {
      WebElement element = driver.findElement(By.id("verifybutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 113 | click | id=storeinput |  | 
    driver.findElement(By.id("verifybutton")).click();
    // 114 | mouseDownAt | id=secondajax | 289,20 | 
    {
      WebElement element = driver.findElement(By.id("storeinput"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 115 | mouseMoveAt | id=secondajax | 289,20 | 
    {
      WebElement element = driver.findElement(By.id("storeinput"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 116 | mouseUpAt | id=secondajax | 289,20 | 
    {
      WebElement element = driver.findElement(By.id("storeinput"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 117 | click | id=secondajax |  | 
    driver.findElement(By.id("storeinput")).click();
    // 118 | doubleClick | id=secondajax |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 119 | doubleClick | id=secondajax |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 120 | doubleClick | id=secondajax |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 121 | mouseDownAt | id=selecttype | 103,10 | 
    driver.findElement(By.id("secondajax")).click();
    // 122 | mouseMoveAt | id=selecttype | 103,10 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 123 | mouseUpAt | id=selecttype | 103,10 | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 124 | click | id=selecttype |  | 
    {
      WebElement element = driver.findElement(By.id("secondajax"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 125 | select | id=selecttype | label=Selenium Core | 
    {
      WebElement element = driver.findElement(By.id("selecttype"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 126 | select | id=selecttype | label=Selenium Core | 
    {
      WebElement element = driver.findElement(By.id("selecttype"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 127 | select | id=selecttype | label=Selenium Core | 
    {
      WebElement element = driver.findElement(By.id("selecttype"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 128 | click | id=selecttype |  | 
    driver.findElement(By.id("selecttype")).click();
    // 129 | mouseDownAt | id=radiobutton | 7,5 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Core']")).click();
    }
    // 130 | mouseMoveAt | id=radiobutton | 7,5 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Core']")).click();
    }
    // 131 | mouseUpAt | id=radiobutton | 7,5 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Core']")).click();
    }
    // 132 | click | id=radiobutton |  | 
    driver.findElement(By.id("selecttype")).click();
    // 133 | mouseDownAt | css=p:nth-child(3) | 51,1 | 
    {
      WebElement element = driver.findElement(By.id("radiobutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 134 | mouseMoveAt | css=p:nth-child(3) | 51,1 | 
    {
      WebElement element = driver.findElement(By.id("radiobutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 135 | mouseUpAt | css=p:nth-child(3) | 51,1 | 
    {
      WebElement element = driver.findElement(By.id("radiobutton"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 136 | click | css=p:nth-child(3) |  | 
    driver.findElement(By.id("radiobutton")).click();
    // 137 | select | id=selecttype | label=Selenium RC | 
    {
      WebElement element = driver.findElement(By.cssSelector("p:nth-child(3)"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 138 | select | id=selecttype | label=Selenium RC | 
    {
      WebElement element = driver.findElement(By.cssSelector("p:nth-child(3)"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 139 | select | id=selecttype | label=Selenium RC | 
    {
      WebElement element = driver.findElement(By.cssSelector("p:nth-child(3)"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 140 | click | id=selecttype |  | 
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    // 141 | mouseDownAt | id=selecttype | 82,6 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium RC']")).click();
    }
    // 142 | mouseMoveAt | id=selecttype | 82,6 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium RC']")).click();
    }
    // 143 | mouseUpAt | id=selecttype | 82,6 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium RC']")).click();
    }
    // 144 | click | id=selecttype |  | 
    driver.findElement(By.id("selecttype")).click();
    // 145 | select | id=selecttype | label=Selenium Grid | 
    {
      WebElement element = driver.findElement(By.id("selecttype"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 146 | select | id=selecttype | label=Selenium Grid | 
    {
      WebElement element = driver.findElement(By.id("selecttype"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 147 | select | id=selecttype | label=Selenium Grid | 
    {
      WebElement element = driver.findElement(By.id("selecttype"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 148 | click | id=selecttype |  | 
    driver.findElement(By.id("selecttype")).click();
    // 149 | mouseDownAt | css=.mainbody | 66,56 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Grid']")).click();
    }
    // 150 | mouseMoveAt | css=.mainbody | 66,56 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Grid']")).click();
    }
    // 151 | mouseUpAt | css=.mainbody | 66,56 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Grid']")).click();
    }
    // 152 | click | css=.mainbody |  | 
    driver.findElement(By.id("selecttype")).click();
    // 153 | select | id=selecttype | label=Selenium IDE | 
    {
      WebElement element = driver.findElement(By.cssSelector(".mainbody"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 154 | select | id=selecttype | label=Selenium IDE | 
    {
      WebElement element = driver.findElement(By.cssSelector(".mainbody"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 155 | select | id=selecttype | label=Selenium IDE | 
    {
      WebElement element = driver.findElement(By.cssSelector(".mainbody"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 156 | click | id=selecttype |  | 
    driver.findElement(By.cssSelector(".mainbody")).click();
    // 157 | mouseDownAt | linkText=Home Page | 37,6 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium IDE']")).click();
    }
    // 158 | mouseMoveAt | linkText=Home Page | 37,6 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium IDE']")).click();
    }
    // 159 | mouseUpAt | linkText=Home Page | 37,6 | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium IDE']")).click();
    }
    // 160 | click | linkText=Home Page |  | 
    driver.findElement(By.id("selecttype")).click();
    // 161 | click | linkText=Chapter2 |  | 
    {
      WebElement element = driver.findElement(By.linkText("Home Page"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 162 | click | name=verifybutton |  | 
    {
      WebElement element = driver.findElement(By.linkText("Home Page"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 163 | click | name=verifybutton1 |  | 
    {
      WebElement element = driver.findElement(By.linkText("Home Page"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 164 | click | id=but1 |  | 
    driver.findElement(By.linkText("Home Page")).click();
    // 165 | click | css=#divontheleft > input:nth-child(3) |  | 
    driver.findElement(By.linkText("Chapter2")).click();
    // 166 | click | name=but2 |  | 
    driver.findElement(By.name("verifybutton")).click();
    // 167 | click | id=random |  | 
    driver.findElement(By.name("verifybutton1")).click();
    // 168 | click | id=random |  | 
    driver.findElement(By.id("but1")).click();
    // 169 | click | id=random |  | 
    driver.findElement(By.cssSelector("#divontheleft > input:nth-child(3)")).click();
    // 170 | click | linkText=Index |  | 
    driver.findElement(By.name("but2")).click();
    // 171 | click | linkText=Chapter3 |  | 
    driver.findElement(By.id("random")).click();
    // 172 | click | id=leftdiv |  | 
    driver.findElement(By.id("random")).click();
    // 173 | click | css=html |  | 
    driver.findElement(By.id("random")).click();
    // 174 | click | id=divinthecenter |  | 
    driver.findElement(By.linkText("Index")).click();
    // 175 | click | id=divinthecenter |  | 
    driver.findElement(By.linkText("Chapter3")).click();
    // 176 | doubleClick | id=divinthecenter |  | 
    driver.findElement(By.id("leftdiv")).click();
    // 177 | click | id=leftdiv |  | 
    driver.findElement(By.cssSelector("html")).click();
    // 178 | click | css=html |  | 
    driver.findElement(By.id("divinthecenter")).click();
    // 179 | click | id=leftdiv |  | 
    driver.findElement(By.id("divinthecenter")).click();
    // 180 | mouseDownAt | id=index | 10,5 | 
    {
      WebElement element = driver.findElement(By.id("divinthecenter"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 181 | mouseMoveAt | id=index | 10,5 | 
    driver.findElement(By.id("leftdiv")).click();
    // 182 | mouseUpAt | id=index | 10,5 | 
    driver.findElement(By.cssSelector("html")).click();
    // 183 | click | id=index |  | 
    driver.findElement(By.id("leftdiv")).click();
    // 184 | click | linkText=Chapter4 |  | 
    {
      WebElement element = driver.findElement(By.id("index"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 185 | click | id=dateInput |  | 
    {
      WebElement element = driver.findElement(By.id("index"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 186 | type | id=dateInput | 45 | 
    {
      WebElement element = driver.findElement(By.id("index"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 187 | click | id=selecttype |  | 
    driver.findElement(By.id("index")).click();
    // 188 | select | id=selecttype | label=Selenium Core | 
    driver.findElement(By.linkText("Chapter4")).click();
    // 189 | click | id=selecttype |  | 
    driver.findElement(By.id("dateInput")).click();
    // 190 | click | id=nextBid |  | 
    driver.findElement(By.id("dateInput")).sendKeys("45");
    // 191 | type | id=nextBid | 55 | 
    driver.findElement(By.id("selecttype")).click();
    // 192 | sendKeys | id=nextBid | ${KEY_ENTER} | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium Core']")).click();
    }
    // 193 | click | id=selectLoad |  | 
    driver.findElement(By.id("selecttype")).click();
    // 194 | click | id=ajaxLoad |  | 
    driver.findElement(By.id("nextBid")).click();
    // 195 | click | css=.mainbody |  | 
    driver.findElement(By.id("nextBid")).sendKeys("55");
    // 196 | click | id=blurry |  | 
    driver.findElement(By.id("nextBid")).sendKeys(Keys.ENTER);
    // 197 | type | id=blurry | 100 | 
    driver.findElement(By.id("selectLoad")).click();
    // 198 | sendKeys | id=blurry | ${KEY_ENTER} | 
    driver.findElement(By.id("ajaxLoad")).click();
    // 199 | assertAlert | 100 |  | 
    driver.findElement(By.cssSelector(".mainbody")).click();
    // 200 | mouseDownAt | id=blurry | 104,16 | 
    driver.findElement(By.id("blurry")).click();
    // 201 | mouseMoveAt | id=blurry | 104,16 | 
    driver.findElement(By.id("blurry")).sendKeys("100");
    // 202 | mouseUpAt | id=blurry | 104,16 | 
    driver.findElement(By.id("blurry")).sendKeys(Keys.ENTER);
    // 203 | click | id=blurry |  | 
    assertThat(driver.switchTo().alert().getText(), is("100"));
    // 204 | type | id=blurry | 100hhh | 
    {
      WebElement element = driver.findElement(By.id("blurry"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 205 | sendKeys | id=blurry | ${KEY_ENTER} | 
    {
      WebElement element = driver.findElement(By.id("blurry"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 206 | click | id=blurry |  | 
    {
      WebElement element = driver.findElement(By.id("blurry"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 207 | assertAlert | 100hhh |  | 
    driver.findElement(By.id("blurry")).click();
    // 208 | mouseDownAt | id=selectLoad | 70,9 | 
    driver.findElement(By.id("blurry")).sendKeys("100hhh");
    // 209 | mouseMoveAt | id=selectLoad | 70,9 | 
    driver.findElement(By.id("blurry")).sendKeys(Keys.ENTER);
    // 210 | mouseUpAt | id=selectLoad | 70,9 | 
    driver.findElement(By.id("blurry")).click();
    // 211 | click | id=selectLoad |  | 
    assertThat(driver.switchTo().alert().getText(), is("100hhh"));
    // 212 | click | id=selecttype |  | 
    {
      WebElement element = driver.findElement(By.id("selectLoad"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 213 | select | id=selecttype | label=Selenium IDE | 
    {
      WebElement element = driver.findElement(By.id("selectLoad"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 214 | click | id=selecttype |  | 
    {
      WebElement element = driver.findElement(By.id("selectLoad"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 215 | click | id=selectLoad |  | 
    driver.findElement(By.id("selectLoad")).click();
    // 216 | click | id=auction |  | 
    driver.findElement(By.id("selecttype")).click();
    // 217 | click | id=nextBid |  | 
    {
      WebElement dropdown = driver.findElement(By.id("selecttype"));
      dropdown.findElement(By.xpath("//option[. = 'Selenium IDE']")).click();
    }
    // 218 | type | id=nextBid | 5500 | 
    driver.findElement(By.id("selecttype")).click();
    // 219 | sendKeys | id=nextBid | ${KEY_ENTER} | 
    driver.findElement(By.id("selectLoad")).click();
    // 220 | click | id=auction |  | 
    driver.findElement(By.id("auction")).click();
    // 221 | click | id=index |  | 
    driver.findElement(By.id("nextBid")).click();
    // 222 | click | linkText=Chapter8 |  | 
    driver.findElement(By.id("nextBid")).sendKeys("5500");
    // 223 | click | id=secondCookie |  | 
    driver.findElement(By.id("nextBid")).sendKeys(Keys.ENTER);
    // 224 | click | id=secondCookie |  | 
    driver.findElement(By.id("auction")).click();
    // 225 | click | id=q |  | 
    driver.findElement(By.id("index")).click();
    // 226 | type | id=q | bcnbnn | 
    driver.findElement(By.linkText("Chapter8")).click();
    // 227 | sendKeys | id=q | ${KEY_ENTER} | 
    driver.findElement(By.id("secondCookie")).click();
    // 228 | close |  |  | 
    driver.findElement(By.id("secondCookie")).click();
    driver.findElement(By.id("q")).click();
    driver.findElement(By.id("q")).sendKeys("bcnbnn");
    driver.findElement(By.id("q")).sendKeys(Keys.ENTER);
    driver.close();
  }
}
