package CrackSeleniumInterviewExamples;
// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

public class Ch4_Prog_1_SeleniumIDE_SeleniumHQTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void seleniumhq() {
        driver.get("https://www.seleniumhq.org/");
        driver.manage().window().setSize(new Dimension(1050, 708));
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.linkText("Download")).click();
        driver.findElement(By.linkText("Download")).click();
        driver.findElement(By.cssSelector(".sectionDownload")).click();
        driver.findElement(By.linkText("Browser Automation")).click();
        driver.findElement(By.cssSelector("td:nth-child(2) .icon")).click();
        driver.findElement(By.linkText("Docs")).click();
        driver.findElement(By.linkText("Code Export")).click();
        driver.findElement(By.linkText("JavaScript Mocha")).click();
        driver.findElement(By.linkText("Plugins")).click();
        driver.findElement(By.linkText("Emitting Code")).click();
        driver.findElement(By.linkText("Error Handling")).click();
    }
}
