// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('DuckDuckGo', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('DuckDuckGo', async function() {
    // Test name: DuckDuckGo
    // Step # | name | target | value | comment
    // 1 | open | https://duckduckgo.com/ |  |
    await driver.get("https://duckduckgo.com/")
    // 2 | setWindowSize | 927x514 |  |
    //await driver.setRect(927, 514)
    // 3 | type | id=search_form_input_homepage | selenium |
    await driver.findElement(By.id("search_form_input_homepage")).sendKeys("selenium")
    // 4 | sendKeys | id=search_form_input_homepage | ${KEY_ENTER} |
    await driver.findElement(By.id("search_form_input_homepage")).sendKeys(Key.ENTER)
    // 5 | click | linkText=Selenium - Web Browser Automation |  |
    await driver.findElement(By.linkText("Selenium - Web Browser Automation")).click()
    // 6 | close |  |  |
    await driver.close()
  })
})
