// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('DemoNewTours', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('DemoNewTours', async function() {
    // Test name: DemoNewTours
    // Step # | name | target | value | comment
    // 1 | open | http://newtours.demoaut.com/ |  | 
    await driver.get("http://newtours.demoaut.com/")
    // 2 | setWindowSize | 1050x708 |  | 
    await driver.setRect(1050, 708)
    // 3 | click | linkText=REGISTER |  | 
    await driver.findElement(By.linkText("REGISTER")).click()
    // 4 | click | css=form tr:nth-child(1) > td |  | 
    await driver.findElement(By.css("form tr:nth-child(1) > td")).click()
    // 5 | click | name=firstName |  | 
    await driver.findElement(By.name("firstName")).click()
    // 6 | type | name=firstName | Selenium | 
    await driver.findElement(By.name("firstName")).sendKeys("Selenium")
    // 7 | type | name=lastName | User | 
    await driver.findElement(By.name("lastName")).sendKeys("User")
    // 8 | type | name=phone | 987-654-3241 | 
    await driver.findElement(By.name("phone")).sendKeys("987-654-3241")
    // 9 | type | id=userName | abc@def.com | 
    await driver.findElement(By.id("userName")).sendKeys("abc@def.com")
    // 10 | type | name=address1 | 12345, Sixth Street | 
    await driver.findElement(By.name("address1")).sendKeys("12345, Sixth Street")
    // 11 | type | name=address2 | Seventh Avenue | 
    await driver.findElement(By.name("address2")).sendKeys("Seventh Avenue")
    // 12 | type | name=city | Denver | 
    await driver.findElement(By.name("city")).sendKeys("Denver")
    // 13 | type | name=state | Colorado | 
    await driver.findElement(By.name("state")).sendKeys("Colorado")
    // 14 | type | name=postalCode | 80201 | 
    await driver.findElement(By.name("postalCode")).sendKeys("80201")
    // 15 | click | id=email |  | 
    await driver.findElement(By.id("email")).click()
    // 16 | type | id=email | selenium_tester1 | 
    await driver.findElement(By.id("email")).sendKeys("selenium_tester1")
    // 17 | type | name=password | password | 
    await driver.findElement(By.name("password")).sendKeys("password")
    // 18 | type | name=confirmPassword | password | 
    await driver.findElement(By.name("confirmPassword")).sendKeys("password")
    // 19 | click | name=register |  | 
    await driver.findElement(By.name("register")).click()
    // 20 | click | linkText=Home |  | 
    await driver.findElement(By.linkText("Home")).click()
    // 21 | click | name=login |  | 
    await driver.findElement(By.name("login")).click()
    // 22 | click | name=fromPort |  | 
    await driver.findElement(By.name("fromPort")).click()
    // 23 | select | name=fromPort | label=Sydney | 
    {
      const dropdown = await driver.findElement(By.name("fromPort"))
      await dropdown.findElement(By.xpath("//option[. = 'Sydney']")).click()
    }
    // 24 | click | name=fromPort |  | 
    await driver.findElement(By.name("fromPort")).click()
    // 25 | click | name=toPort |  | 
    await driver.findElement(By.name("toPort")).click()
    // 26 | select | name=toPort | label=New York | 
    {
      const dropdown = await driver.findElement(By.name("toPort"))
      await dropdown.findElement(By.xpath("//option[. = 'New York']")).click()
    }
    // 27 | click | name=toPort |  | 
    await driver.findElement(By.name("toPort")).click()
    // 28 | click | css=input:nth-child(4) |  | 
    await driver.findElement(By.css("input:nth-child(4)")).click()
    // 29 | click | name=airline |  | 
    await driver.findElement(By.name("airline")).click()
    // 30 | select | name=airline | label=Unified Airlines | 
    {
      const dropdown = await driver.findElement(By.name("airline"))
      await dropdown.findElement(By.xpath("//option[. = 'Unified Airlines']")).click()
    }
    // 31 | click | name=airline |  | 
    await driver.findElement(By.name("airline")).click()
    // 32 | click | name=findFlights |  | 
    await driver.findElement(By.name("findFlights")).click()
    // 33 | click | css=table:nth-child(9) tr:nth-child(9) input |  | 
    await driver.findElement(By.css("table:nth-child(9) tr:nth-child(9) input")).click()
    // 34 | click | css=table:nth-child(10) tr:nth-child(9) > .frame_action_xrows |  | 
    await driver.findElement(By.css("table:nth-child(10) tr:nth-child(9) > .frame_action_xrows")).click()
    // 35 | click | css=table:nth-child(10) tr:nth-child(9) input |  | 
    await driver.findElement(By.css("table:nth-child(10) tr:nth-child(9) input")).click()
    // 36 | click | name=reserveFlights |  | 
    await driver.findElement(By.name("reserveFlights")).click()
    // 37 | click | css=table:nth-child(20) > tbody > tr:nth-child(4) > td |  | 
    await driver.findElement(By.css("table:nth-child(20) > tbody > tr:nth-child(4) > td")).click()
    // 38 | click | name=passFirst0 |  | 
    await driver.findElement(By.name("passFirst0")).click()
    // 39 | click | name=passFirst0 |  | 
    await driver.findElement(By.name("passFirst0")).click()
    // 40 | doubleClick | name=passFirst0 |  | 
    {
      const element = await driver.findElement(By.name("passFirst0"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 41 | click | css=table:nth-child(20) tr:nth-child(4) tr:nth-child(1) > td:nth-child(1) |  | 
    await driver.findElement(By.css("table:nth-child(20) tr:nth-child(4) tr:nth-child(1) > td:nth-child(1)")).click()
    // 42 | click | name=passFirst0 |  | 
    await driver.findElement(By.name("passFirst0")).click()
    // 43 | type | name=passFirst0 | Traveller | 
    await driver.findElement(By.name("passFirst0")).sendKeys("Traveller")
    // 44 | type | name=passLast0 | Tester | 
    await driver.findElement(By.name("passLast0")).sendKeys("Tester")
    // 45 | click | css=tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td:nth-child(3)")).click()
    // 46 | click | name=pass.0.meal |  | 
    await driver.findElement(By.name("pass.0.meal")).click()
    // 47 | select | name=pass.0.meal | label=Vegetarian | 
    {
      const dropdown = await driver.findElement(By.name("pass.0.meal"))
      await dropdown.findElement(By.xpath("//option[. = 'Vegetarian']")).click()
    }
    // 48 | click | name=pass.0.meal |  | 
    await driver.findElement(By.name("pass.0.meal")).click()
    // 49 | click | name=creditCard |  | 
    await driver.findElement(By.name("creditCard")).click()
    // 50 | select | name=creditCard | label=Visa | 
    {
      const dropdown = await driver.findElement(By.name("creditCard"))
      await dropdown.findElement(By.xpath("//option[. = 'Visa']")).click()
    }
    // 51 | click | name=creditCard |  | 
    await driver.findElement(By.name("creditCard")).click()
    // 52 | click | css=tr:nth-child(7) tr:nth-child(2) > td:nth-child(2) |  | 
    await driver.findElement(By.css("tr:nth-child(7) tr:nth-child(2) > td:nth-child(2)")).click()
    // 53 | type | name=creditnumber | 1234567890123456 | 
    await driver.findElement(By.name("creditnumber")).sendKeys("1234567890123456")
    // 54 | click | name=cc_exp_dt_mn |  | 
    await driver.findElement(By.name("cc_exp_dt_mn")).click()
    // 55 | select | name=cc_exp_dt_mn | label=11 | 
    {
      const dropdown = await driver.findElement(By.name("cc_exp_dt_mn"))
      await dropdown.findElement(By.xpath("//option[. = '11']")).click()
    }
    // 56 | click | name=cc_exp_dt_mn |  | 
    await driver.findElement(By.name("cc_exp_dt_mn")).click()
    // 57 | click | name=cc_exp_dt_yr |  | 
    await driver.findElement(By.name("cc_exp_dt_yr")).click()
    // 58 | select | name=cc_exp_dt_yr | label=2010 | 
    {
      const dropdown = await driver.findElement(By.name("cc_exp_dt_yr"))
      await dropdown.findElement(By.xpath("//option[. = '2010']")).click()
    }
    // 59 | click | name=cc_exp_dt_yr |  | 
    await driver.findElement(By.name("cc_exp_dt_yr")).click()
    // 60 | click | name=cc_frst_name |  | 
    await driver.findElement(By.name("cc_frst_name")).click()
    // 61 | click | css=tr:nth-child(8) tr:nth-child(1) > td:nth-child(1) |  | 
    await driver.findElement(By.css("tr:nth-child(8) tr:nth-child(1) > td:nth-child(1)")).click()
    // 62 | click | name=passFirst0 |  | 
    await driver.findElement(By.name("passFirst0")).click()
    // 63 | click | name=passFirst0 |  | 
    await driver.findElement(By.name("passFirst0")).click()
    // 64 | doubleClick | name=passFirst0 |  | 
    {
      const element = await driver.findElement(By.name("passFirst0"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 65 | click | css=tr:nth-child(8) tbody |  | 
    await driver.findElement(By.css("tr:nth-child(8) tbody")).click()
    // 66 | click | name=cc_frst_name |  | 
    await driver.findElement(By.name("cc_frst_name")).click()
    // 67 | type | name=cc_frst_name | Traveller | 
    await driver.findElement(By.name("cc_frst_name")).sendKeys("Traveller")
    // 68 | click | name=passLast0 |  | 
    await driver.findElement(By.name("passLast0")).click()
    // 69 | click | name=passLast0 |  | 
    await driver.findElement(By.name("passLast0")).click()
    // 70 | doubleClick | name=passLast0 |  | 
    {
      const element = await driver.findElement(By.name("passLast0"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 71 | click | name=cc_last_name |  | 
    await driver.findElement(By.name("cc_last_name")).click()
    // 72 | type | name=cc_last_name | Tester | 
    await driver.findElement(By.name("cc_last_name")).sendKeys("Tester")
    // 73 | click | name=cc_mid_name |  | 
    await driver.findElement(By.name("cc_mid_name")).click()
    // 74 | click | css=tr:nth-child(15) input |  | 
    await driver.findElement(By.css("tr:nth-child(15) input")).click()
    // 75 | click | name=ticketLess |  | 
    await driver.findElement(By.name("ticketLess")).click()
    // 76 | click | name=buyFlights |  | 
    await driver.findElement(By.name("buyFlights")).click()
    // 77 | click | css=font > img |  | 
    await driver.findElement(By.css("font > img")).click()
    // 78 | click | css=font > img |  | 
    await driver.findElement(By.css("font > img")).click()
    // 79 | click | css=td:nth-child(1) > a > img |  | 
    await driver.findElement(By.css("td:nth-child(1) > a > img")).click()
    // 80 | click | linkText=Flights |  | 
    await driver.findElement(By.linkText("Flights")).click()
    // 81 | click | linkText=Hotels |  | 
    await driver.findElement(By.linkText("Hotels")).click()
    // 82 | click | css=a > img |  | 
    await driver.findElement(By.css("a > img")).click()
    // 83 | click | linkText=Car Rentals |  | 
    await driver.findElement(By.linkText("Car Rentals")).click()
    // 84 | click | linkText=Cruises |  | 
    await driver.findElement(By.linkText("Cruises")).click()
    // 85 | click | css=td:nth-child(1) td:nth-child(1) > img:nth-child(1) |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(1) > img:nth-child(1)")).click()
    // 86 | click | linkText=Destinations |  | 
    await driver.findElement(By.linkText("Destinations")).click()
    // 87 | click | linkText=Vacations |  | 
    await driver.findElement(By.linkText("Vacations")).click()
    // 88 | click | linkText=Home |  | 
    await driver.findElement(By.linkText("Home")).click()
    // 89 | click | linkText=Flights |  | 
    await driver.findElement(By.linkText("Flights")).click()
    // 90 | click | name=login |  | 
    await driver.findElement(By.name("login")).click()
    // 91 | click | linkText=ITINERARY |  | 
    await driver.findElement(By.linkText("ITINERARY")).click()
    // 92 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 93 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 94 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 95 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 96 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 97 | click | css=.\_hsShareImage |  | 
    await driver.findElement(By.css(".\_hsShareImage")).click()
    // 98 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 99 | storeWindowHandle | root |  | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 100 | selectWindow | handle=${win5947} |  | 
    vars["win5947"] = await waitForWindow(2000)
    // 101 | close |  |  | 
    vars["root"] = await driver.getWindowHandle()
    // 102 | selectWindow | handle=${root} |  | 
    await driver.switchTo().window(vars["win5947"])
    // 103 | click | css=td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1) |  | 
    await driver.close()
    // 104 | mouseDownAt | css=area | 345,-82 | 
    await driver.switchTo().window(vars["root"])
    // 105 | mouseMoveAt | css=area | 345,-82 | 
    await driver.findElement(By.css("td:nth-child(1) td:nth-child(2) tr:nth-child(1) img:nth-child(1)")).click()
    // 106 | mouseUpAt | css=area | 345,-82 | 
    {
      const element = await driver.findElement(By.css("area"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 107 | click | css=area |  | 
    {
      const element = await driver.findElement(By.css("area"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 108 | mouseDownAt | css=area | 352,-82 | 
    {
      const element = await driver.findElement(By.css("area"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 109 | mouseMoveAt | css=area | 352,-82 | 
    await driver.findElement(By.css("area")).click()
    // 110 | mouseUpAt | css=area | 352,-82 | 
    {
      const element = await driver.findElement(By.css("area"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 111 | click | css=area |  | 
    {
      const element = await driver.findElement(By.css("area"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 112 | type | name=userName | selenium_tester1 | 
    {
      const element = await driver.findElement(By.css("area"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 113 | type | name=password | password | 
    await driver.findElement(By.css("area")).click()
    // 114 | click | name=login |  | 
    await driver.findElement(By.name("userName")).sendKeys("selenium_tester1")
    // 115 | click | name=toPort |  | 
    await driver.findElement(By.name("password")).sendKeys("password")
    // 116 | select | name=toPort | label=Sydney | 
    await driver.findElement(By.name("login")).click()
    // 117 | click | name=toPort |  | 
    await driver.findElement(By.name("toPort")).click()
    // 118 | click | name=toDay |  | 
    {
      const dropdown = await driver.findElement(By.name("toPort"))
      await dropdown.findElement(By.xpath("//option[. = 'Sydney']")).click()
    }
    // 119 | click | name=toMonth |  | 
    await driver.findElement(By.name("toPort")).click()
    // 120 | select | name=toMonth | label=November | 
    await driver.findElement(By.name("toDay")).click()
    // 121 | click | name=toMonth |  | 
    await driver.findElement(By.name("toMonth")).click()
    // 122 | click | name=airline |  | 
    {
      const dropdown = await driver.findElement(By.name("toMonth"))
      await dropdown.findElement(By.xpath("//option[. = 'November']")).click()
    }
    // 123 | click | css=tr:nth-child(9) > td:nth-child(2) |  | 
    await driver.findElement(By.name("toMonth")).click()
    // 124 | click | name=findFlights |  | 
    await driver.findElement(By.name("airline")).click()
    // 125 | click | css=table:nth-child(10) tr:nth-child(7) > .frame_action_xrows |  | 
    await driver.findElement(By.css("tr:nth-child(9) > td:nth-child(2)")).click()
    // 126 | click | css=table:nth-child(10) tr:nth-child(7) input |  | 
    await driver.findElement(By.name("findFlights")).click()
    // 127 | click | name=reserveFlights |  | 
    await driver.findElement(By.css("table:nth-child(10) tr:nth-child(7) > .frame_action_xrows")).click()
    // 128 | type | name=passFirst0 | Selenium | 
    await driver.findElement(By.css("table:nth-child(10) tr:nth-child(7) input")).click()
    // 129 | type | name=passLast0 | User | 
    await driver.findElement(By.name("reserveFlights")).click()
    // 130 | click | name=cc_frst_name |  | 
    await driver.findElement(By.name("passFirst0")).sendKeys("Selenium")
    // 131 | click | name=cc_frst_name |  | 
    await driver.findElement(By.name("passLast0")).sendKeys("User")
    // 132 | doubleClick | name=cc_frst_name |  | 
    await driver.findElement(By.name("cc_frst_name")).click()
    // 133 | type | name=cc_frst_name | Selenium | 
    await driver.findElement(By.name("cc_frst_name")).click()
    // 134 | type | name=cc_last_name | User | 
    {
      const element = await driver.findElement(By.name("cc_frst_name"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 135 | type | name=billAddress2 | Seventh Avenue | 
    await driver.findElement(By.name("cc_frst_name")).sendKeys("Selenium")
    // 136 | click | name=creditCard |  | 
    await driver.findElement(By.name("cc_last_name")).sendKeys("User")
    // 137 | select | name=creditCard | label=Visa | 
    await driver.findElement(By.name("billAddress2")).sendKeys("Seventh Avenue")
    // 138 | click | name=creditCard |  | 
    await driver.findElement(By.name("creditCard")).click()
    // 139 | click | css=table:nth-child(20) > tbody > tr:nth-child(9) > td:nth-child(1) |  | 
    {
      const dropdown = await driver.findElement(By.name("creditCard"))
      await dropdown.findElement(By.xpath("//option[. = 'Visa']")).click()
    }
    // 140 | click | name=creditnumber |  | 
    await driver.findElement(By.name("creditCard")).click()
    // 141 | type | name=creditnumber | 1234567890123456 | 
    await driver.findElement(By.css("table:nth-child(20) > tbody > tr:nth-child(9) > td:nth-child(1)")).click()
    // 142 | click | name=cc_exp_dt_mn |  | 
    await driver.findElement(By.name("creditnumber")).click()
    // 143 | select | name=cc_exp_dt_mn | label=11 | 
    await driver.findElement(By.name("creditnumber")).sendKeys("1234567890123456")
    // 144 | click | name=cc_exp_dt_mn |  | 
    await driver.findElement(By.name("cc_exp_dt_mn")).click()
    // 145 | click | css=tr:nth-child(7) tr:nth-child(2) > td:nth-child(3) |  | 
    {
      const dropdown = await driver.findElement(By.name("cc_exp_dt_mn"))
      await dropdown.findElement(By.xpath("//option[. = '11']")).click()
    }
    // 146 | click | name=cc_exp_dt_yr |  | 
    await driver.findElement(By.name("cc_exp_dt_mn")).click()
    // 147 | select | name=cc_exp_dt_yr | label=2010 | 
    await driver.findElement(By.css("tr:nth-child(7) tr:nth-child(2) > td:nth-child(3)")).click()
    // 148 | click | name=cc_exp_dt_yr |  | 
    await driver.findElement(By.name("cc_exp_dt_yr")).click()
    // 149 | click | css=body > div |  | 
    {
      const dropdown = await driver.findElement(By.name("cc_exp_dt_yr"))
      await dropdown.findElement(By.xpath("//option[. = '2010']")).click()
    }
    // 150 | click | name=ticketLess |  | 
    await driver.findElement(By.name("cc_exp_dt_yr")).click()
    // 151 | click | css=tr:nth-child(15) input |  | 
    await driver.findElement(By.css("body > div")).click()
    // 152 | click | name=buyFlights |  | 
    await driver.findElement(By.name("ticketLess")).click()
    // 153 | click | css=font > img |  | 
    await driver.findElement(By.css("tr:nth-child(15) input")).click()
    // 154 | click | css=font > img |  | 
    await driver.findElement(By.name("buyFlights")).click()
    // 155 | doubleClick | css=font > img |  | 
    await driver.findElement(By.css("font > img")).click()
    // 156 | click | css=td:nth-child(1) tr:nth-child(1) > td:nth-child(1) > img:nth-child(1) |  | 
    await driver.findElement(By.css("font > img")).click()
    // 157 | click | css=td:nth-child(2) > a > img |  | 
    {
      const element = await driver.findElement(By.css("font > img"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 158 | click | linkText=SUPPORT |  | 
    await driver.findElement(By.css("td:nth-child(1) tr:nth-child(1) > td:nth-child(1) > img:nth-child(1)")).click()
    // 159 | click | css=a > img |  | 
    await driver.findElement(By.css("td:nth-child(2) > a > img")).click()
    // 160 | click | linkText=CONTACT |  | 
    await driver.findElement(By.linkText("SUPPORT")).click()
    // 161 | click | css=a > img |  | 
    await driver.findElement(By.css("a > img")).click()
    // 162 | click | css=p:nth-child(4) > img |  | 
    await driver.findElement(By.linkText("CONTACT")).click()
    // 163 | click | css=table:nth-child(3) tr:nth-child(3) img |  | 
    await driver.findElement(By.css("a > img")).click()
    // 164 | click | css=tr:nth-child(10) img |  | 
    await driver.findElement(By.css("p:nth-child(4) > img")).click()
    // 165 | click | css=a:nth-child(2) |  | 
    await driver.findElement(By.css("table:nth-child(3) tr:nth-child(3) img")).click()
    // 166 | selectWindow | handle=${win37} |  | 
    await driver.findElement(By.css("tr:nth-child(10) img")).click()
    // 167 | close |  |  | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 168 | selectWindow | handle=${root} |  | 
    await driver.findElement(By.css("a:nth-child(2)")).click()
    // 169 | click | linkText=featured vacation destinations |  | 
    vars["win37"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win37"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.linkText("featured vacation destinations")).click()
  })
})
