// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(600000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    // Test name: Untitled
    // Step # | name | target | value | comment
    // 1 | open | / |  |
    await driver.get("https://www.dogpile.com/")
    // 2 | setWindowSize | 927x514 |  |
    //await driver.setRect(927, 514)
    // 3 | click | id=q |  |
    await driver.findElement(By.id("q")).click()
    // 4 | type | id=q | selenium |
    await driver.findElement(By.id("q")).sendKeys("selenium")
    // 5 | sendKeys | id=q | ${KEY_ENTER} |
    await driver.findElement(By.id("q")).sendKeys(Key.ENTER)
    // 6 | click | css=.aylf-bing-sidebar__result:nth-child(9) > .aylf-bing-sidebar__title |  |
    await driver.findElement(By.css(".aylf-bing-sidebar__result:nth-child(9) > .aylf-bing-sidebar__title")).click()
    // 7 | close |  |  |
    await driver.close()
  })
})
