// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SeleniumDemoTestSite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('SeleniumDemoTestSite', async function() {
    // Test name: SeleniumDemoTestSite
    // Step # | name | target | value | comment
    // 1 | open | https://www.seleniumeasy.com/test/ |  | 
    await driver.get("https://www.seleniumeasy.com/test/")
    // 2 | setWindowSize | 1382x744 |  | 
    await driver.setRect(1382, 744)
    // 3 | verifyTitle | Selenium Easy - Best Demo website to practice Selenium Webdriver Online |  | 
    assert(await driver.getTitle() == "Selenium Easy - Best Demo website to practice Selenium Webdriver Online")
    // 4 | assertTitle | Selenium Easy - Best Demo website to practice Selenium Webdriver Online |  | 
    assert(await driver.getTitle() == "Selenium Easy - Best Demo website to practice Selenium Webdriver Online")
    // 5 | assertText | id=navbar-brand-centered | Input Forms\nDate pickers\nTable\nProgress Bars\nAlerts & Modals\nList Box\nOthers | 
    assert(await driver.findElement(By.id("navbar-brand-centered")).getText() == "Input Forms\nDate pickers\nTable\nProgress Bars\nAlerts & Modals\nList Box\nOthers")
    // 6 | mouseOver | css=.glyphicon-home |  | 
    {
      const element = await driver.findElement(By.css(".glyphicon-home"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | mouseOut | css=.glyphicon-home |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 8 | mouseDownAt | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right | 9,6 | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(1) > .glyphicon-chevron-right"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 9 | mouseMoveAt | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right | 9,6 | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(1) > .glyphicon-chevron-right"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | mouseUpAt | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right | 9,6 | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(1) > .glyphicon-chevron-right"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 11 | click | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(1) > .glyphicon-chevron-right")).click()
    // 12 | mouseDownAt | linkText=Simple Form Demo | 53,10 | 
    {
      const element = await driver.findElement(By.linkText("Simple Form Demo"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 13 | mouseMoveAt | linkText=Simple Form Demo | 53,10 | 
    {
      const element = await driver.findElement(By.linkText("Simple Form Demo"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | mouseUpAt | linkText=Simple Form Demo | 53,10 | 
    {
      const element = await driver.findElement(By.linkText("Simple Form Demo"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 15 | click | linkText=Simple Form Demo |  | 
    await driver.findElement(By.linkText("Simple Form Demo")).click()
    // 16 | click | id=user-message |  | 
    await driver.findElement(By.id("user-message")).click()
    // 17 | click | id=user-message |  | 
    await driver.findElement(By.id("user-message")).click()
    // 18 | type | id=user-message | Testing Selenium Demo | 
    await driver.findElement(By.id("user-message")).sendKeys("Testing Selenium Demo")
    // 19 | click | css=.btn:nth-child(2) |  | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 20 | click | id=sum1 |  | 
    await driver.findElement(By.id("sum1")).click()
    // 21 | type | id=sum1 | 100 | 
    await driver.findElement(By.id("sum1")).sendKeys("100")
    // 22 | click | id=sum2 |  | 
    await driver.findElement(By.id("sum2")).click()
    // 23 | type | id=sum2 | 200 | 
    await driver.findElement(By.id("sum2")).sendKeys("200")
    // 24 | click | css=.btn:nth-child(3) |  | 
    await driver.findElement(By.css(".btn:nth-child(3)")).click()
    // 25 | click | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(1) > .glyphicon-chevron-right")).click()
    // 26 | click | linkText=Checkbox Demo |  | 
    await driver.findElement(By.linkText("Checkbox Demo")).click()
    // 27 | click | id=isAgeSelected |  | 
    await driver.findElement(By.id("isAgeSelected")).click()
    // 28 | click | css=.checkbox:nth-child(3) .cb1-element |  | 
    await driver.findElement(By.css(".checkbox:nth-child(3) .cb1-element")).click()
    // 29 | click | css=.checkbox:nth-child(5) .cb1-element |  | 
    await driver.findElement(By.css(".checkbox:nth-child(5) .cb1-element")).click()
    // 30 | click | id=check1 |  | 
    await driver.findElement(By.id("check1")).click()
    // 31 | click | id=check1 |  | 
    await driver.findElement(By.id("check1")).click()
    // 32 | click | css=.checkbox:nth-child(3) .cb1-element |  | 
    await driver.findElement(By.css(".checkbox:nth-child(3) .cb1-element")).click()
    // 33 | click | css=.checkbox:nth-child(5) .cb1-element |  | 
    await driver.findElement(By.css(".checkbox:nth-child(5) .cb1-element")).click()
    // 34 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    await driver.findElement(By.css("ul:nth-child(3) > .tree-branch:nth-child(1) > a")).click()
    // 35 | click | linkText=Radio Buttons Demo |  | 
    await driver.findElement(By.linkText("Radio Buttons Demo")).click()
    // 36 | click | css=.panel-body > .radio-inline:nth-child(3) > input |  | 
    await driver.findElement(By.css(".panel-body > .radio-inline:nth-child(3) > input")).click()
    // 37 | click | id=buttoncheck |  | 
    await driver.findElement(By.id("buttoncheck")).click()
    // 38 | click | name=optradio |  | 
    await driver.findElement(By.name("optradio")).click()
    // 39 | click | id=buttoncheck |  | 
    await driver.findElement(By.id("buttoncheck")).click()
    // 40 | click | css=.panel:nth-child(5) > .panel-body |  | 
    await driver.findElement(By.css(".panel:nth-child(5) > .panel-body")).click()
    // 41 | click | name=gender |  | 
    await driver.findElement(By.name("gender")).click()
    // 42 | click | css=.radio-inline:nth-child(4) > input |  | 
    await driver.findElement(By.css(".radio-inline:nth-child(4) > input")).click()
    // 43 | click | css=.btn:nth-child(5) |  | 
    await driver.findElement(By.css(".btn:nth-child(5)")).click()
    // 44 | click | css=.panel-body > div:nth-child(2) > .radio-inline:nth-child(3) |  | 
    await driver.findElement(By.css(".panel-body > div:nth-child(2) > .radio-inline:nth-child(3)")).click()
    // 45 | click | css=div:nth-child(3) > .radio-inline:nth-child(3) > input |  | 
    await driver.findElement(By.css("div:nth-child(3) > .radio-inline:nth-child(3) > input")).click()
    // 46 | click | css=.btn:nth-child(5) |  | 
    await driver.findElement(By.css(".btn:nth-child(5)")).click()
    // 47 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    await driver.findElement(By.css("ul:nth-child(3) > .tree-branch:nth-child(1) > a")).click()
    // 48 | click | linkText=Radio Buttons Demo |  | 
    await driver.findElement(By.linkText("Radio Buttons Demo")).click()
    // 49 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    await driver.findElement(By.css("ul:nth-child(3) > .tree-branch:nth-child(1) > a")).click()
    // 50 | click | linkText=Select Dropdown List |  | 
    await driver.findElement(By.linkText("Select Dropdown List")).click()
    // 51 | click | id=select-demo |  | 
    await driver.findElement(By.id("select-demo")).click()
    // 52 | select | id=select-demo | label=Tuesday | 
    {
      const dropdown = await driver.findElement(By.id("select-demo"))
      await dropdown.findElement(By.xpath("//option[. = 'Tuesday']")).click()
    }
    // 53 | click | id=select-demo |  | 
    await driver.findElement(By.id("select-demo")).click()
    // 54 | click | id=select-demo |  | 
    await driver.findElement(By.id("select-demo")).click()
    // 55 | select | id=select-demo | label=Friday | 
    {
      const dropdown = await driver.findElement(By.id("select-demo"))
      await dropdown.findElement(By.xpath("//option[. = 'Friday']")).click()
    }
    // 56 | click | id=select-demo |  | 
    await driver.findElement(By.id("select-demo")).click()
    // 57 | addSelection | id=multi-select | label=New Jersey | 
    {
      const dropdown = await driver.findElement(By.id("multi-select"))
      await dropdown.findElement(By.xpath("//option[. = 'New Jersey']")).click()
    }
    // 58 | addSelection | id=multi-select | label=Pennsylvania | 
    {
      const dropdown = await driver.findElement(By.id("multi-select"))
      await dropdown.findElement(By.xpath("//option[. = 'Pennsylvania']")).click()
    }
    // 59 | addSelection | id=multi-select | label=California | 
    {
      const dropdown = await driver.findElement(By.id("multi-select"))
      await dropdown.findElement(By.xpath("//option[. = 'California']")).click()
    }
    // 60 | click | id=printMe |  | 
    await driver.findElement(By.id("printMe")).click()
    // 61 | click | id=printMe |  | 
    await driver.findElement(By.id("printMe")).click()
    // 62 | click | id=printAll |  | 
    await driver.findElement(By.id("printAll")).click()
    // 63 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    await driver.findElement(By.css("ul:nth-child(3) > .tree-branch:nth-child(1) > a")).click()
    // 64 | click | linkText=Ajax Form Submit |  | 
    await driver.findElement(By.linkText("Ajax Form Submit")).click()
    // 65 | click | id=title |  | 
    await driver.findElement(By.id("title")).click()
    // 66 | type | id=title | Selenium Test | 
    await driver.findElement(By.id("title")).sendKeys("Selenium Test")
    // 67 | type | id=description | Test Tested again and again! | 
    await driver.findElement(By.id("description")).sendKeys("Test Tested again and again!")
    // 68 | click | id=btn-submit |  | 
    await driver.findElement(By.id("btn-submit")).click()
    // 69 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    await driver.findElement(By.css("ul:nth-child(3) > .tree-branch:nth-child(1) > a")).click()
    // 70 | click | linkText=JQuery Select dropdown |  | 
    await driver.findElement(By.linkText("JQuery Select dropdown")).click()
    // 71 | click | css=.row > h3 |  | 
    await driver.findElement(By.css(".row > h3")).click()
    // 72 | click | css=.select2-search__field |  | 
    await driver.findElement(By.css(".select2-search__field")).click()
    // 73 | click | css=.panel:nth-child(2) > .panel-heading |  | 
    await driver.findElement(By.css(".panel:nth-child(2) > .panel-heading")).click()
    // 74 | click | css=.select2-search__field |  | 
    await driver.findElement(By.css(".select2-search__field")).click()
    // 75 | click | css=.select2-selection--multiple > .select2-selection__rendered |  | 
    await driver.findElement(By.css(".select2-selection--multiple > .select2-selection__rendered")).click()
    // 76 | click | css=.select2-selection--multiple > .select2-selection__rendered |  | 
    await driver.findElement(By.css(".select2-selection--multiple > .select2-selection__rendered")).click()
    // 77 | click | id=select2-niq4-container |  | 
    await driver.findElement(By.id("select2-niq4-container")).click()
    // 78 | click | id=files |  | 
    await driver.findElement(By.id("files")).click()
    // 79 | select | id=files | label=Java | 
    {
      const dropdown = await driver.findElement(By.id("files"))
      await dropdown.findElement(By.xpath("//option[. = 'Java']")).click()
    }
    // 80 | click | id=files |  | 
    await driver.findElement(By.id("files")).click()
    // 81 | click | css=.row:nth-child(5) .panel-body |  | 
    await driver.findElement(By.css(".row:nth-child(5) .panel-body")).click()
    // 82 | click | id=files |  | 
    await driver.findElement(By.id("files")).click()
    // 83 | click | id=files |  | 
    await driver.findElement(By.id("files")).click()
    // 84 | click | css=.text-center > .row |  | 
    await driver.findElement(By.css(".text-center > .row")).click()
    // 85 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    await driver.findElement(By.css("ul:nth-child(3) > .tree-branch:nth-child(1) > a")).click()
    // 86 | click | css=.tree-branch:nth-child(2) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(2) > a")).click()
    // 87 | click | linkText=Bootstrap Date Picker |  | 
    await driver.findElement(By.linkText("Bootstrap Date Picker")).click()
    // 88 | click | css=.glyphicon-th |  | 
    await driver.findElement(By.css(".glyphicon-th")).click()
    // 89 | click | css=tr:nth-child(2) > .day:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(2) > .day:nth-child(3)")).click()
    // 90 | click | css=.glyphicon-th |  | 
    await driver.findElement(By.css(".glyphicon-th")).click()
    // 91 | click | css=.datepicker-days .datepicker-switch |  | 
    await driver.findElement(By.css(".datepicker-days .datepicker-switch")).click()
    // 92 | click | css=.month:nth-child(6) |  | 
    await driver.findElement(By.css(".month:nth-child(6)")).click()
    // 93 | click | css=.datepicker-days .datepicker-switch |  | 
    await driver.findElement(By.css(".datepicker-days .datepicker-switch")).click()
    // 94 | click | css=.datepicker-months .datepicker-switch |  | 
    await driver.findElement(By.css(".datepicker-months .datepicker-switch")).click()
    // 95 | click | css=.year:nth-child(2) |  | 
    await driver.findElement(By.css(".year:nth-child(2)")).click()
    // 96 | click | css=.month:nth-child(6) |  | 
    await driver.findElement(By.css(".month:nth-child(6)")).click()
    // 97 | click | css=tr:nth-child(3) > .day:nth-child(4) |  | 
    await driver.findElement(By.css("tr:nth-child(3) > .day:nth-child(4)")).click()
    // 98 | runScript | window.scrollTo(0,500) |  | 
    await driver.executeScript("window.scrollTo(0,500)")
    // 99 | click | css=#datepicker > .form-control:nth-child(1) |  | 
    await driver.findElement(By.css("#datepicker > .form-control:nth-child(1)")).click()
    // 100 | click | css=tr:nth-child(3) > .day:nth-child(4) |  | 
    await driver.findElement(By.css("tr:nth-child(3) > .day:nth-child(4)")).click()
    // 101 | click | css=.datepicker-days .datepicker-switch |  | 
    await driver.findElement(By.css(".datepicker-days .datepicker-switch")).click()
    // 102 | click | css=.datepicker-months .datepicker-switch |  | 
    await driver.findElement(By.css(".datepicker-months .datepicker-switch")).click()
    // 103 | click | css=.year:nth-child(1) |  | 
    await driver.findElement(By.css(".year:nth-child(1)")).click()
    // 104 | click | css=.month:nth-child(6) |  | 
    await driver.findElement(By.css(".month:nth-child(6)")).click()
    // 105 | click | css=tr:nth-child(3) > .day:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(3) > .day:nth-child(3)")).click()
    // 106 | click | css=.row:nth-child(3) .panel-body |  | 
    await driver.findElement(By.css(".row:nth-child(3) .panel-body")).click()
    // 107 | click | css=.form-control:nth-child(3) |  | 
    await driver.findElement(By.css(".form-control:nth-child(3)")).click()
    // 108 | click | css=tr:nth-child(2) > .range:nth-child(4) |  | 
    await driver.findElement(By.css("tr:nth-child(2) > .range:nth-child(4)")).click()
    // 109 | click | css=.text-center > .row |  | 
    await driver.findElement(By.css(".text-center > .row")).click()
    // 110 | click | css=.tree-branch:nth-child(2) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(2) > a")).click()
    // 111 | click | linkText=JQuery Date Picker |  | 
    await driver.findElement(By.linkText("JQuery Date Picker")).click()
    // 112 | type | id=to | 10/10/2011 | 
    await driver.findElement(By.id("to")).sendKeys("10/10/2011")
    // 113 | click | css=p:nth-child(4) |  | 
    await driver.findElement(By.css("p:nth-child(4)")).click()
    // 114 | click | id=to |  | 
    await driver.findElement(By.id("to")).click()
    // 115 | click | css=tr:nth-child(2) > td:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(3)")).click()
    // 116 | click | id=from |  | 
    await driver.findElement(By.id("from")).click()
    // 117 | click | css=tr:nth-child(3) > td:nth-child(4) |  | 
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(4)")).click()
    // 118 | click | css=.text-left |  | 
    await driver.findElement(By.css(".text-left")).click()
    // 119 | click | css=.tree-branch:nth-child(2) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(2) > a")).click()
    // 120 | click | css=.tree-branch:nth-child(3) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(3) > a")).click()
    // 121 | click | linkText=Table Pagination |  | 
    await driver.findElement(By.linkText("Table Pagination")).click()
    // 122 | click | linkText=Table Pagination |  | 
    await driver.findElement(By.linkText("Table Pagination")).click()
    // 123 | click | linkText=2 |  | 
    await driver.findElement(By.linkText("2")).click()
    // 124 | click | linkText=3 |  | 
    await driver.findElement(By.linkText("3")).click()
    // 125 | click | css=tr:nth-child(11) > td:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(11) > td:nth-child(3)")).click()
    // 126 | click | css=tr:nth-child(12) > td:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(12) > td:nth-child(3)")).click()
    // 127 | click | css=tr:nth-child(12) > td:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(12) > td:nth-child(3)")).click()
    // 128 | click | css=tr:nth-child(12) > td:nth-child(3) |  | 
    await driver.findElement(By.css("tr:nth-child(12) > td:nth-child(3)")).click()
    // 129 | click | css=.tree-branch:nth-child(3) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(3) > a")).click()
    // 130 | click | linkText=Table Data Search |  | 
    await driver.findElement(By.linkText("Table Data Search")).click()
    // 131 | click | id=task-table-filter |  | 
    await driver.findElement(By.id("task-table-filter")).click()
    // 132 | type | id=task-table-filter | wire | 
    await driver.findElement(By.id("task-table-filter")).sendKeys("wire")
    // 133 | click | css=.clickable > .glyphicon |  | 
    await driver.findElement(By.css(".clickable > .glyphicon")).click()
    // 134 | click | css=h2 |  | 
    await driver.findElement(By.css("h2")).click()
    // 135 | click | css=.text-center > .row |  | 
    await driver.findElement(By.css(".text-center > .row")).click()
    // 136 | type | id=task-table-filter | joh | 
    await driver.findElement(By.id("task-table-filter")).sendKeys("joh")
    // 137 | click | css=th:nth-child(1) > .form-control |  | 
    await driver.findElement(By.css("th:nth-child(1) > .form-control")).click()
    // 138 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 139 | click | css=th:nth-child(1) > .form-control |  | 
    await driver.findElement(By.css("th:nth-child(1) > .form-control")).click()
    // 140 | click | css=.text-center > .row |  | 
    await driver.findElement(By.css(".text-center > .row")).click()
    // 141 | click | css=.text-center > .row |  | 
    await driver.findElement(By.css(".text-center > .row")).click()
    // 142 | type | css=th:nth-child(1) > .form-control | 2 | 
    await driver.findElement(By.css("th:nth-child(1) > .form-control")).sendKeys("2")
    // 143 | click | css=.tree-branch:nth-child(3) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(3) > a")).click()
    // 144 | click | linkText=Table Filter |  | 
    await driver.findElement(By.linkText("Table Filter")).click()
    // 145 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 146 | click | css=tr:nth-child(1) label |  | 
    await driver.findElement(By.css("tr:nth-child(1) label")).click()
    // 147 | click | css=.btn-warning |  | 
    await driver.findElement(By.css(".btn-warning")).click()
    // 148 | click | css=tr:nth-child(2) label |  | 
    await driver.findElement(By.css("tr:nth-child(2) label")).click()
    // 149 | click | css=tr:nth-child(5) label |  | 
    await driver.findElement(By.css("tr:nth-child(5) label")).click()
    // 150 | click | css=.btn-danger |  | 
    await driver.findElement(By.css(".btn-danger")).click()
    // 151 | click | css=tr:nth-child(3) label |  | 
    await driver.findElement(By.css("tr:nth-child(3) label")).click()
    // 152 | click | css=.btn-default |  | 
    await driver.findElement(By.css(".btn-default")).click()
    // 153 | click | css=.selected:nth-child(3) label |  | 
    await driver.findElement(By.css(".selected:nth-child(3) label")).click()
    // 154 | click | css=.selected:nth-child(1) label |  | 
    await driver.findElement(By.css(".selected:nth-child(1) label")).click()
    // 155 | click | css=.tree-branch:nth-child(3) > .tree-indicator |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(3) > .tree-indicator")).click()
    // 156 | click | linkText=Table Sort & Search |  | 
    await driver.findElement(By.linkText("Table Sort & Search")).click()
    // 157 | click | name=example_length |  | 
    await driver.findElement(By.name("example_length")).click()
    // 158 | select | name=example_length | label=100 | 
    {
      const dropdown = await driver.findElement(By.name("example_length"))
      await dropdown.findElement(By.xpath("//option[. = '100']")).click()
    }
    // 159 | click | name=example_length |  | 
    await driver.findElement(By.name("example_length")).click()
    // 160 | click | css=.sorting:nth-child(2) |  | 
    await driver.findElement(By.css(".sorting:nth-child(2)")).click()
    // 161 | click | css=.tree-branch:nth-child(3) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(3) > a")).click()
    // 162 | click | css=input |  | 
    await driver.findElement(By.css("input")).click()
    // 163 | type | css=input | tokyo | 
    await driver.findElement(By.css("input")).sendKeys("tokyo")
    // 164 | sendKeys | css=input | ${KEY_ENTER} | 
    await driver.findElement(By.css("input")).sendKeys(Key.ENTER)
    // 165 | click | linkText=Table Data Download |  | 
    await driver.findElement(By.linkText("Table Data Download")).click()
    // 166 | click | css=th:nth-child(3) |  | 
    await driver.findElement(By.css("th:nth-child(3)")).click()
    // 167 | click | css=tr:nth-child(7) > td:nth-child(2) |  | 
    await driver.findElement(By.css("tr:nth-child(7) > td:nth-child(2)")).click()
    // 168 | click | css=tr:nth-child(7) > td:nth-child(2) |  | 
    await driver.findElement(By.css("tr:nth-child(7) > td:nth-child(2)")).click()
    // 169 | doubleClick | css=tr:nth-child(7) > td:nth-child(2) |  | 
    {
      const element = await driver.findElement(By.css("tr:nth-child(7) > td:nth-child(2)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 170 | click | linkText=Progress Bars & Sliders |  | 
    await driver.findElement(By.linkText("Progress Bars & Sliders")).click()
    // 171 | click | css=.tree-branch:nth-child(3) |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(3)")).click()
    // 172 | click | css=th:nth-child(1) |  | 
    await driver.findElement(By.css("th:nth-child(1)")).click()
    // 173 | click | css=th:nth-child(1) |  | 
    await driver.findElement(By.css("th:nth-child(1)")).click()
    // 174 | doubleClick | css=th:nth-child(1) |  | 
    {
      const element = await driver.findElement(By.css("th:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 175 | click | css=th:nth-child(2) |  | 
    await driver.findElement(By.css("th:nth-child(2)")).click()
    // 176 | click | css=th:nth-child(3) |  | 
    await driver.findElement(By.css("th:nth-child(3)")).click()
    // 177 | click | linkText=JQuery Download Progress bars |  | 
    await driver.findElement(By.linkText("JQuery Download Progress bars")).click()
    // 178 | click | id=downloadButton |  | 
    await driver.findElement(By.id("downloadButton")).click()
    // 179 | click | css=.ui-dialog-buttonset > button |  | 
    await driver.findElement(By.css(".ui-dialog-buttonset > button")).click()
    // 180 | click | linkText=Progress Bars & Sliders |  | 
    await driver.findElement(By.linkText("Progress Bars & Sliders")).click()
    // 181 | click | linkText=JQuery Download Progress bars |  | 
    await driver.findElement(By.linkText("JQuery Download Progress bars")).click()
    // 182 | click | id=downloadButton |  | 
    await driver.findElement(By.id("downloadButton")).click()
    // 183 | click | css=.ui-dialog-buttonset > button |  | 
    await driver.findElement(By.css(".ui-dialog-buttonset > button")).click()
    // 184 | click | css=.tree-branch:nth-child(4) |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(4)")).click()
    // 185 | click | linkText=JQuery Download Progress bars |  | 
    await driver.findElement(By.linkText("JQuery Download Progress bars")).click()
    // 186 | click | id=downloadButton |  | 
    await driver.findElement(By.id("downloadButton")).click()
    // 187 | click | css=.ui-dialog-buttonset > button |  | 
    await driver.findElement(By.css(".ui-dialog-buttonset > button")).click()
    // 188 | click | css=.tree-branch:nth-child(4) > .tree-indicator |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(4) > .tree-indicator")).click()
    // 189 | click | linkText=Bootstrap Progress bar |  | 
    await driver.findElement(By.linkText("Bootstrap Progress bar")).click()
    // 190 | click | id=cricle-btn |  | 
    await driver.findElement(By.id("cricle-btn")).click()
    // 191 | click | id=cricle-btn |  | 
    await driver.findElement(By.id("cricle-btn")).click()
    // 192 | click | linkText=Progress Bars & Sliders |  | 
    await driver.findElement(By.linkText("Progress Bars & Sliders")).click()
    // 193 | click | linkText=Drag & Drop Sliders |  | 
    await driver.findElement(By.linkText("Drag & Drop Sliders")).click()
    // 194 | type | name=range | 32 | 
    await driver.findElement(By.name("range")).sendKeys("32")
    // 195 | click | name=range |  | 
    await driver.findElement(By.name("range")).click()
    // 196 | type | css=.range-primary > input | 79 | 
    await driver.findElement(By.css(".range-primary > input")).sendKeys("79")
    // 197 | click | css=.range-primary > input |  | 
    await driver.findElement(By.css(".range-primary > input")).click()
    // 198 | type | css=.range-success > input | 53 | 
    await driver.findElement(By.css(".range-success > input")).sendKeys("53")
    // 199 | click | css=.range-success > input |  | 
    await driver.findElement(By.css(".range-success > input")).click()
    // 200 | mouseDownAt | css=.range-success > input | 209.75,11 | 
    {
      const element = await driver.findElement(By.css(".range-success > input"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 201 | mouseMoveAt | css=.range-success > input | 209.75,11 | 
    {
      const element = await driver.findElement(By.css(".range-success > input"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 202 | mouseUpAt | css=.range-success > input | 209.75,11 | 
    {
      const element = await driver.findElement(By.css(".range-success > input"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 203 | type | css=.range-success > input | 80 | 
    await driver.findElement(By.css(".range-success > input")).sendKeys("80")
    // 204 | click | css=.range-success > input |  | 
    await driver.findElement(By.css(".range-success > input")).click()
    // 205 | mouseDownAt | css=.range-info > input | 50.5,1 | 
    {
      const element = await driver.findElement(By.css(".range-info > input"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 206 | mouseMoveAt | css=.range-info > input | 50.5,1 | 
    {
      const element = await driver.findElement(By.css(".range-info > input"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 207 | mouseUpAt | css=.range-info > input | 50.5,1 | 
    {
      const element = await driver.findElement(By.css(".range-info > input"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 208 | type | css=.range-info > input | 18 | 
    await driver.findElement(By.css(".range-info > input")).sendKeys("18")
    // 209 | click | css=.range-info > input |  | 
    await driver.findElement(By.css(".range-info > input")).click()
    // 210 | type | css=.range-danger > input | 79 | 
    await driver.findElement(By.css(".range-danger > input")).sendKeys("79")
    // 211 | click | css=.range-danger > input |  | 
    await driver.findElement(By.css(".range-danger > input")).click()
    // 212 | type | css=.range-danger > input | 1 | 
    await driver.findElement(By.css(".range-danger > input")).sendKeys("1")
    // 213 | click | css=.range-danger > input |  | 
    await driver.findElement(By.css(".range-danger > input")).click()
    // 214 | type | css=.range-warning > input | 70 | 
    await driver.findElement(By.css(".range-warning > input")).sendKeys("70")
    // 215 | click | css=.range-warning > input |  | 
    await driver.findElement(By.css(".range-warning > input")).click()
    // 216 | click | css=.tree-branch:nth-child(4) |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(4)")).click()
    // 217 | click | linkText=JQuery Download Progress bars |  | 
    await driver.findElement(By.linkText("JQuery Download Progress bars")).click()
    // 218 | click | id=downloadButton |  | 
    await driver.findElement(By.id("downloadButton")).click()
    // 219 | click | css=.ui-dialog-buttonset > button |  | 
    await driver.findElement(By.css(".ui-dialog-buttonset > button")).click()
    // 220 | click | linkText=Progress Bars & Sliders |  | 
    await driver.findElement(By.linkText("Progress Bars & Sliders")).click()
    // 221 | click | linkText=JQuery Download Progress bars |  | 
    await driver.findElement(By.linkText("JQuery Download Progress bars")).click()
    // 222 | click | id=downloadButton |  | 
    await driver.findElement(By.id("downloadButton")).click()
    // 223 | click | css=.ui-dialog-buttonset > button |  | 
    await driver.findElement(By.css(".ui-dialog-buttonset > button")).click()
    // 224 | click | linkText=Progress Bars & Sliders |  | 
    await driver.findElement(By.linkText("Progress Bars & Sliders")).click()
    // 225 | click | css=.tree-branch:nth-child(5) |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5)")).click()
    // 226 | click | linkText=Bootstrap Alerts |  | 
    await driver.findElement(By.linkText("Bootstrap Alerts")).click()
    // 227 | click | id=autoclosable-btn-success |  | 
    await driver.findElement(By.id("autoclosable-btn-success")).click()
    // 228 | click | id=normal-btn-success |  | 
    await driver.findElement(By.id("normal-btn-success")).click()
    // 229 | click | id=autoclosable-btn-warning |  | 
    await driver.findElement(By.id("autoclosable-btn-warning")).click()
    // 230 | click | id=normal-btn-warning |  | 
    await driver.findElement(By.id("normal-btn-warning")).click()
    // 231 | click | id=autoclosable-btn-danger |  | 
    await driver.findElement(By.id("autoclosable-btn-danger")).click()
    // 232 | click | id=normal-btn-danger |  | 
    await driver.findElement(By.id("normal-btn-danger")).click()
    // 233 | click | id=autoclosable-btn-info |  | 
    await driver.findElement(By.id("autoclosable-btn-info")).click()
    // 234 | click | id=normal-btn-info |  | 
    await driver.findElement(By.id("normal-btn-info")).click()
    // 235 | click | css=.footer |  | 
    await driver.findElement(By.css(".footer")).click()
    // 236 | click | id=autoclosable-btn-info |  | 
    await driver.findElement(By.id("autoclosable-btn-info")).click()
    // 237 | click | css=.tree-branch:nth-child(5) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5) > a")).click()
    // 238 | click | linkText=Bootstrap Modals |  | 
    await driver.findElement(By.linkText("Bootstrap Modals")).click()
    // 239 | click | linkText=Launch modal |  | 
    await driver.findElement(By.linkText("Launch modal")).click()
    // 240 | click | linkText=Close |  | 
    await driver.findElement(By.linkText("Close")).click()
    // 241 | click | linkText=Launch modal |  | 
    await driver.findElement(By.linkText("Launch modal")).click()
    // 242 | mouseOver | linkText=Launch modal |  | 
    {
      const element = await driver.findElement(By.linkText("Launch modal"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 243 | mouseOut | linkText=Launch modal |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 244 | click | linkText=Save changes |  | 
    await driver.findElement(By.linkText("Save changes")).click()
    // 245 | click | css=.row:nth-child(3) .panel-body > .btn |  | 
    await driver.findElement(By.css(".row:nth-child(3) .panel-body > .btn")).click()
    // 246 | mouseOver | css=.row:nth-child(3) .panel-body > .btn |  | 
    {
      const element = await driver.findElement(By.css(".row:nth-child(3) .panel-body > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 247 | mouseOut | css=.row:nth-child(3) .panel-body > .btn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 248 | click | css=.btn:nth-child(7) |  | 
    await driver.findElement(By.css(".btn:nth-child(7)")).click()
    // 249 | mouseOver | css=.btn:nth-child(7) |  | 
    {
      const element = await driver.findElement(By.css(".btn:nth-child(7)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 250 | mouseOut | css=.btn:nth-child(7) |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 251 | click | css=.modal-footer:nth-child(6) > .btn:nth-child(1) |  | 
    await driver.findElement(By.css(".modal-footer:nth-child(6) > .btn:nth-child(1)")).click()
    // 252 | click | linkText=Close |  | 
    await driver.findElement(By.linkText("Close")).click()
    // 253 | click | css=.tree-branch:nth-child(5) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5) > a")).click()
    // 254 | click | linkText=Window Popup Modal |  | 
    await driver.findElement(By.linkText("Window Popup Modal")).click()
    // 255 | click | linkText=Follow On Twitter |  | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 256 | storeWindowHandle | root |  | 
    await driver.findElement(By.linkText("Follow On Twitter")).click()
    // 257 | selectWindow | handle=${win8669} |  | 
    vars["win8669"] = await waitForWindow(2000)
    // 258 | close |  |  | 
    vars["root"] = await driver.getWindowHandle()
    // 259 | selectWindow | handle=${root} |  | 
    await driver.switchTo().window(vars["win8669"])
    // 260 | mouseOver | linkText=Like us On Facebook |  | 
    await driver.close()
    // 261 | click | linkText=Like us On Facebook |  | 
    await driver.switchTo().window(vars["root"])
    // 262 | mouseOut | linkText=Like us On Facebook |  | 
    {
      const element = await driver.findElement(By.linkText("Like us On Facebook"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 263 | selectWindow | handle=${win6493} |  | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 264 | close |  |  | 
    await driver.findElement(By.linkText("Like us On Facebook")).click()
    // 265 | selectWindow | handle=${root} |  | 
    vars["win6493"] = await waitForWindow(2000)
    // 266 | mouseDownAt | linkText=Follow Twitter & Facebook | 159.75,14 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 267 | mouseMoveAt | linkText=Follow Twitter & Facebook | 159.75,14 | 
    await driver.switchTo().window(vars["win6493"])
    // 268 | mouseUpAt | linkText=Follow Twitter & Facebook | 159.75,14 | 
    await driver.close()
    // 269 | click | linkText=Follow Twitter & Facebook |  | 
    await driver.switchTo().window(vars["root"])
    // 270 | selectWindow | handle=${win5817} |  | 
    {
      const element = await driver.findElement(By.linkText("Follow Twitter & Facebook"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 271 | verifyTitle | Selenium Easy (@seleniumeasy) on Twitter |  | 
    {
      const element = await driver.findElement(By.linkText("Follow Twitter & Facebook"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 272 | close |  |  | 
    {
      const element = await driver.findElement(By.linkText("Follow Twitter & Facebook"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 273 | selectWindow | handle=${root} |  | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 274 | mouseOver | linkText=Follow Twitter & Facebook |  | 
    await driver.findElement(By.linkText("Follow Twitter & Facebook")).click()
    // 275 | mouseOut | linkText=Follow Twitter & Facebook |  | 
    vars["win5817"] = await waitForWindow(2000)
    // 276 | mouseDownAt | id=followall | 64.75,20 | 
    await driver.switchTo().window(vars["win5817"])
    // 277 | mouseMoveAt | id=followall | 64.75,20 | 
    assert(await driver.getTitle() == "Selenium Easy (@seleniumeasy) on Twitter")
    // 278 | mouseUpAt | id=followall | 64.75,20 | 
    await driver.close()
    // 279 | click | id=followall |  | 
    await driver.switchTo().window(vars["root"])
    // 280 | selectWindow | handle=${win4983} |  | 
    {
      const element = await driver.findElement(By.linkText("Follow Twitter & Facebook"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 281 | close |  |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 282 | selectWindow | handle=${root} |  | 
    {
      const element = await driver.findElement(By.id("followall"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 283 | mouseDownAt | css=.tree-branch:nth-child(5) > a | 57.125,5 | 
    {
      const element = await driver.findElement(By.id("followall"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 284 | mouseMoveAt | css=.tree-branch:nth-child(5) > a | 57.125,5 | 
    {
      const element = await driver.findElement(By.id("followall"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 285 | mouseUpAt | css=.tree-branch:nth-child(5) > a | 57.125,5 | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 286 | click | css=.tree-branch:nth-child(5) > a |  | 
    await driver.findElement(By.id("followall")).click()
    // 287 | mouseDownAt | css=.tree-branch:nth-child(6) > a | 27.125,7 | 
    vars["win4983"] = await waitForWindow(2000)
    // 288 | mouseMoveAt | css=.tree-branch:nth-child(6) > a | 27.125,7 | 
    await driver.switchTo().window(vars["win4983"])
    // 289 | mouseUpAt | css=.tree-branch:nth-child(6) > a | 27.125,7 | 
    await driver.close()
    // 290 | click | css=.tree-branch:nth-child(6) > a |  | 
    await driver.switchTo().window(vars["root"])
    // 291 | mouseDownAt | linkText=Progress Bar Modal | 96,4 | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(5) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 292 | mouseMoveAt | linkText=Progress Bar Modal | 96,4 | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(5) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 293 | mouseUpAt | linkText=Progress Bar Modal | 96,4 | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(5) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 294 | click | linkText=Progress Bar Modal |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5) > a")).click()
    // 295 | click | css=.btn-primary |  | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(6) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 296 | click | css=.btn-success |  | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(6) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 297 | click | css=.btn-warning |  | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(6) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 298 | mouseOver | css=.btn-warning |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(6) > a")).click()
    // 299 | mouseOut | css=.btn-warning |  | 
    {
      const element = await driver.findElement(By.linkText("Progress Bar Modal"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 300 | click | css=.btn-success |  | 
    {
      const element = await driver.findElement(By.linkText("Progress Bar Modal"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 301 | click | css=.btn-warning |  | 
    {
      const element = await driver.findElement(By.linkText("Progress Bar Modal"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 302 | mouseOver | css=.btn-warning |  | 
    await driver.findElement(By.linkText("Progress Bar Modal")).click()
    // 303 | mouseOut | css=.btn-warning |  | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 304 | click | css=.modal |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 305 | click | css=.modal |  | 
    await driver.findElement(By.css(".btn-warning")).click()
    // 306 | click | css=.tree-branch:nth-child(5) > a |  | 
    {
      const element = await driver.findElement(By.css(".btn-warning"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 307 | click | linkText=File Download |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 308 | click | id=textbox |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 309 | type | id=textbox | Testing Selenium | 
    await driver.findElement(By.css(".btn-warning")).click()
    // 310 | click | id=create |  | 
    {
      const element = await driver.findElement(By.css(".btn-warning"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 311 | click | id=link-to-download |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 312 | click | css=.tree-branch:nth-child(5) > a |  | 
    await driver.findElement(By.css(".modal")).click()
    // 313 | click | linkText=Javascript Alerts |  | 
    await driver.findElement(By.css(".modal")).click()
    // 314 | click | css=.panel:nth-child(4) .btn |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5) > a")).click()
    // 315 | assertAlert | I am an alert box! |  | 
    await driver.findElement(By.linkText("File Download")).click()
    // 316 | chooseOkOnNextConfirmation |  |  | 
    await driver.findElement(By.id("textbox")).click()
    // 317 | click | css=.panel:nth-child(5) .btn |  | 
    await driver.findElement(By.id("textbox")).sendKeys("Testing Selenium")
    // 318 | assertConfirmation | Press a button! |  | 
    await driver.findElement(By.id("create")).click()
    // 319 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    await driver.findElement(By.id("link-to-download")).click()
    // 320 | chooseCancelOnNextConfirmation |  |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5) > a")).click()
    // 321 | click | css=.panel:nth-child(5) .btn |  | 
    await driver.findElement(By.linkText("Javascript Alerts")).click()
    // 322 | assertConfirmation | Press a button! |  | 
    await driver.findElement(By.css(".panel:nth-child(4) .btn")).click()
    // 323 | webdriverChooseCancelOnVisibleConfirmation |  |  | 
    assert(await driver.switchTo().alert().getText() == "I am an alert box!")
    // 324 | answerOnNextPrompt | Hello World! |  | 
    // 325 | click | css=.panel:nth-child(6) .btn |  | 
    await driver.findElement(By.css(".panel:nth-child(5) .btn")).click()
    // 326 | assertPrompt | Please enter your name |  | 
    assert(await driver.switchTo().alert().getText() == "Press a button!")
    // 327 | webdriverAnswerOnVisiblePrompt | Hello World! |  | 
    await driver.switchTo().alert().accept()
    // 328 | answerOnNextPrompt | It's OK |  | 
    // 329 | click | css=.panel:nth-child(6) .btn |  | 
    await driver.findElement(By.css(".panel:nth-child(5) .btn")).click()
    // 330 | assertPrompt | Please enter your name |  | 
    assert(await driver.switchTo().alert().getText() == "Press a button!")
    // 331 | webdriverAnswerOnVisiblePrompt | It's OK |  | 
    await driver.switchTo().alert().dismiss()
    // 332 | click | css=.tree-branch:nth-child(5) > a |  | 
    // 333 | click | linkText=Progress Bar Modal |  | 
    await driver.findElement(By.css(".panel:nth-child(6) .btn")).click()
    // 334 | click | css=.tree-branch:nth-child(6) > a |  | 
    assert(await driver.switchTo().alert().getText() == "Please enter your name")
    // 335 | click | linkText=Bootstrap List Box |  | 
    {
      const alert = await driver.switchTo().alert()
      await alert.sendKeys("Hello World!")
      await alert.accept()
    }
    // 336 | click | css=.text-right .list-group-item:nth-child(1) |  | 
    // 337 | click | css=.col-md-2:nth-child(2) .glyphicon |  | 
    await driver.findElement(By.css(".panel:nth-child(6) .btn")).click()
    // 338 | click | css=.move-right |  | 
    assert(await driver.switchTo().alert().getText() == "Please enter your name")
    // 339 | click | css=.list-group-item:nth-child(3) |  | 
    {
      const alert = await driver.switchTo().alert()
      await alert.sendKeys("It\'s OK")
      await alert.accept()
    }
    // 340 | click | css=.glyphicon-chevron-left |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(5) > a")).click()
    // 341 | click | css=.move-right > .glyphicon |  | 
    await driver.findElement(By.linkText("Progress Bar Modal")).click()
    // 342 | click | css=.list-group-item:nth-child(1) |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(6) > a")).click()
    // 343 | click | css=.list-group-item:nth-child(5) |  | 
    await driver.findElement(By.linkText("Bootstrap List Box")).click()
    // 344 | click | css=.list-group-item:nth-child(6) |  | 
    await driver.findElement(By.css(".text-right .list-group-item:nth-child(1)")).click()
    // 345 | click | css=.list-group-item:nth-child(8) |  | 
    await driver.findElement(By.css(".col-md-2:nth-child(2) .glyphicon")).click()
    // 346 | click | css=.list-group-item:nth-child(9) |  | 
    await driver.findElement(By.css(".move-right")).click()
    // 347 | click | css=.move-left |  | 
    await driver.findElement(By.css(".list-group-item:nth-child(3)")).click()
    // 348 | click | css=.form-control:nth-child(1) |  | 
    await driver.findElement(By.css(".glyphicon-chevron-left")).click()
    // 349 | click | css=.form-control:nth-child(1) |  | 
    await driver.findElement(By.css(".move-right > .glyphicon")).click()
    // 350 | click | css=.form-control:nth-child(1) |  | 
    await driver.findElement(By.css(".list-group-item:nth-child(1)")).click()
    // 351 | type | css=.form-control:nth-child(1) | leo | 
    await driver.findElement(By.css(".list-group-item:nth-child(5)")).click()
    // 352 | click | css=.list-group-item:nth-child(4) |  | 
    await driver.findElement(By.css(".list-group-item:nth-child(6)")).click()
    // 353 | click | css=.list-group-item:nth-child(4) |  | 
    await driver.findElement(By.css(".list-group-item:nth-child(8)")).click()
    // 354 | click | css=.list-group-item:nth-child(4) |  | 
    await driver.findElement(By.css(".list-group-item:nth-child(9)")).click()
    // 355 | doubleClick | css=.list-group-item:nth-child(4) |  | 
    await driver.findElement(By.css(".move-left")).click()
    // 356 | click | css=.input-group-addon:nth-child(2) |  | 
    await driver.findElement(By.css(".form-control:nth-child(1)")).click()
    // 357 | click | css=.tree-branch:nth-child(6) > .tree-indicator |  | 
    await driver.findElement(By.css(".form-control:nth-child(1)")).click()
    // 358 | click | linkText=JQuery List Box |  | 
    await driver.findElement(By.css(".form-control:nth-child(1)")).click()
    // 359 | addSelection | css=.pickData | label=Manuela | 
    await driver.findElement(By.css(".form-control:nth-child(1)")).sendKeys("leo")
    // 360 | addSelection | css=.pickData | label=Laura | 
    await driver.findElement(By.css(".list-group-item:nth-child(4)")).click()
    // 361 | addSelection | css=.pickData | label=Luiza | 
    await driver.findElement(By.css(".list-group-item:nth-child(4)")).click()
    // 362 | addSelection | css=.pickData | label=Valentina | 
    await driver.findElement(By.css(".list-group-item:nth-child(4)")).click()
    // 363 | addSelection | css=.pickData | label=Giovanna | 
    {
      const element = await driver.findElement(By.css(".list-group-item:nth-child(4)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 364 | click | css=.pAdd |  | 
    await driver.findElement(By.css(".input-group-addon:nth-child(2)")).click()
    // 365 | addSelection | css=.pickListResult | label=Valentina | 
    await driver.findElement(By.css(".tree-branch:nth-child(6) > .tree-indicator")).click()
    // 366 | click | css=.pRemove |  | 
    await driver.findElement(By.linkText("JQuery List Box")).click()
    // 367 | addSelection | css=.pickData | label=Maria Luiza | 
    {
      const dropdown = await driver.findElement(By.css(".pickData"))
      await dropdown.findElement(By.xpath("//option[. = 'Manuela']")).click()
    }
    // 368 | click | css=.pAdd |  | 
    {
      const dropdown = await driver.findElement(By.css(".pickData"))
      await dropdown.findElement(By.xpath("//option[. = 'Laura']")).click()
    }
    // 369 | click | css=.tree-branch:nth-child(6) > a |  | 
    {
      const dropdown = await driver.findElement(By.css(".pickData"))
      await dropdown.findElement(By.xpath("//option[. = 'Luiza']")).click()
    }
    // 370 | click | linkText=Data List Filter |  | 
    {
      const dropdown = await driver.findElement(By.css(".pickData"))
      await dropdown.findElement(By.xpath("//option[. = 'Valentina']")).click()
    }
    // 371 | click | css=.items:nth-child(1) .glyphicon |  | 
    {
      const dropdown = await driver.findElement(By.css(".pickData"))
      await dropdown.findElement(By.xpath("//option[. = 'Giovanna']")).click()
    }
    // 372 | click | id=input-search |  | 
    await driver.findElement(By.css(".pAdd")).click()
    // 373 | type | id=input-search | Tree | 
    {
      const dropdown = await driver.findElement(By.css(".pickListResult"))
      await dropdown.findElement(By.xpath("//option[. = 'Valentina']")).click()
    }
    // 374 | click | css=.items:nth-child(2) span:nth-child(5) |  | 
    await driver.findElement(By.css(".pRemove")).click()
    // 375 | click | css=.text-center > .row |  | 
    {
      const dropdown = await driver.findElement(By.css(".pickData"))
      await dropdown.findElement(By.xpath("//option[. = 'Maria Luiza']")).click()
    }
    // 376 | type | id=input-search | Hoy | 
    await driver.findElement(By.css(".pAdd")).click()
    // 377 | click | css=.tree-branch:nth-child(6) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(6) > a")).click()
    // 378 | click | css=.tree-branch:nth-child(7) > a |  | 
    await driver.findElement(By.linkText("Data List Filter")).click()
    // 379 | click | linkText=Drag and Drop |  | 
    await driver.findElement(By.css(".items:nth-child(1) .glyphicon")).click()
    // 380 | dragAndDropToObject | css=#todrag > span:nth-child(3) | id=mydropzone | 
    await driver.findElement(By.id("input-search")).click()
    // 381 | dragAndDropToObject | css=#todrag > span:nth-child(2) | id=mydropzone | 
    await driver.findElement(By.id("input-search")).sendKeys("Tree")
    // 382 | click | css=#droppedlist > span:nth-child(1) |  | 
    await driver.findElement(By.css(".items:nth-child(2) span:nth-child(5)")).click()
    // 383 | dragAndDropToObject | css=#todrag > span:nth-child(3) | id=mydropzone | 
    await driver.findElement(By.css(".text-center > .row")).click()
    // 384 | dragAndDropToObject | css=#todrag > span | id=mydropzone | 
    await driver.findElement(By.id("input-search")).sendKeys("Hoy")
    // 385 | click | css=.tree-branch:nth-child(7) > a |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(6) > a")).click()
    // 386 | click | linkText=Dynamic Data Loading |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(7) > a")).click()
    // 387 | click | id=save |  | 
    await driver.findElement(By.linkText("Drag and Drop")).click()
    // 388 | click | css=.panel:nth-child(3) > .panel-body |  | 
    {
      const dragged = await driver.findElement(By.css("#todrag > span:nth-child(3)"))
      const dropped = await driver.findElement(By.id("mydropzone"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    // 389 | click | id=save |  | 
    {
      const dragged = await driver.findElement(By.css("#todrag > span:nth-child(2)"))
      const dropped = await driver.findElement(By.id("mydropzone"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    // 390 | click | id=save |  | 
    await driver.findElement(By.css("#droppedlist > span:nth-child(1)")).click()
    // 391 | click | id=save |  | 
    {
      const dragged = await driver.findElement(By.css("#todrag > span:nth-child(3)"))
      const dropped = await driver.findElement(By.id("mydropzone"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    // 392 | click | id=save |  | 
    {
      const dragged = await driver.findElement(By.css("#todrag > span"))
      const dropped = await driver.findElement(By.id("mydropzone"))
      await driver.actions({ bridge: true }).dragAndDrop(dragged, dropped).perform()
    }
    // 393 | click | id=save |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(7) > a")).click()
    // 394 | click | id=save |  | 
    await driver.findElement(By.linkText("Dynamic Data Loading")).click()
    // 395 | click | id=save |  | 
    await driver.findElement(By.id("save")).click()
    // 396 | click | id=save |  | 
    await driver.findElement(By.css(".panel:nth-child(3) > .panel-body")).click()
    // 397 | click | id=save |  | 
    await driver.findElement(By.id("save")).click()
    // 398 | click | id=save |  | 
    await driver.findElement(By.id("save")).click()
    // 399 | mouseOver | id=save |  | 
    await driver.findElement(By.id("save")).click()
    // 400 | click | id=save |  | 
    await driver.findElement(By.id("save")).click()
    // 401 | mouseOut | id=save |  | 
    await driver.findElement(By.id("save")).click()
    // 402 | mouseOver | css=.tree-branch:nth-child(6) > a |  | 
    await driver.findElement(By.id("save")).click()
    // 403 | mouseOut | css=.tree-branch:nth-child(6) > a |  | 
    await driver.findElement(By.id("save")).click()
    // 404 | click | css=.tree-branch:nth-child(7) > a |  | 
    await driver.findElement(By.id("save")).click()
    // 405 | click | linkText=Dynamic Data Loading |  | 
    await driver.findElement(By.id("save")).click()
    // 406 | click | css=.tree-branch:nth-child(7) > a |  | 
    await driver.findElement(By.id("save")).click()
    // 407 | click | linkText=Charts Demo |  | 
    {
      const element = await driver.findElement(By.id("save"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 408 | click | id=myBarChart |  | 
    await driver.findElement(By.id("save")).click()
    // 409 | click | css=.btn:nth-child(1) |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 410 | click | css=.video > h2 |  | 
    {
      const element = await driver.findElement(By.css(".tree-branch:nth-child(6) > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 411 | click | css=.btn:nth-child(2) |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 412 | assertText | css=.btn:nth-child(2) | PICTURES | 
    await driver.findElement(By.css(".tree-branch:nth-child(7) > a")).click()
    // 413 | verifyTitle | Selenium Easy - Charts Mouse Hover |  | 
    await driver.findElement(By.linkText("Dynamic Data Loading")).click()
    // 414 | click | css=.tree-branch:nth-child(7) |  | 
    await driver.findElement(By.css(".tree-branch:nth-child(7) > a")).click()
    // 415 | click | linkText=Others |  | 
    await driver.findElement(By.linkText("Charts Demo")).click()
    // 416 | click | linkText=List Box |  | 
    await driver.findElement(By.id("myBarChart")).click()
    // 417 | click | linkText=JQuery List Box |  | 
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    // 418 | click | linkText=Input Forms |  | 
    await driver.findElement(By.css(".video > h2")).click()
    // 419 | click | id=site-slogan |  | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 420 | close |  |  | 
    assert(await driver.findElement(By.css(".btn:nth-child(2)")).getText() == "PICTURES")
    assert(await driver.getTitle() == "Selenium Easy - Charts Mouse Hover")
    await driver.findElement(By.css(".tree-branch:nth-child(7)")).click()
    await driver.findElement(By.linkText("Others")).click()
    await driver.findElement(By.linkText("List Box")).click()
    await driver.findElement(By.linkText("JQuery List Box")).click()
    await driver.findElement(By.linkText("Input Forms")).click()
    await driver.findElement(By.id("site-slogan")).click()
    await driver.close()
  })
})
