// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SeleniumHQ Website Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SeleniumHQ Website Test', async function() {
    await driver.get("https://www.seleniumhq.org/")
    await driver.setRect(1050, 708)
    await driver.findElement(By.linkText("Projects")).click()
    await driver.findElement(By.css("p:nth-child(3) > a")).click()
    await driver.findElement(By.linkText("ChromeDriver")).click()
    await driver.findElement(By.linkText("FindsByTagName")).click()
    await driver.findElement(By.linkText("Download")).click()
    await driver.findElement(By.css("table:nth-child(13) tr:nth-child(1) > td:nth-child(4) > a")).click()
    await driver.findElement(By.linkText("Documentation")).click()
    await driver.executeScript("window.scrollTo(0,123)")
    await driver.findElement(By.linkText("Driver Specifics and Tradeoffs")).click()
    await driver.findElement(By.css("#usage > .toggler-python")).click()
    await driver.findElement(By.css("#enabling-javascript > .toggler-csharp")).click()
    await driver.findElement(By.css("#enabling-javascript > .toggler-python")).click()
    await driver.findElement(By.css("#modifying-the-firefox-profile > .toggler:nth-child(5)")).click()
    await driver.findElement(By.css(".toggler-csharp:nth-child(10)")).click()
    await driver.findElement(By.css(".toggler-csharp:nth-child(15)")).click()
    await driver.findElement(By.css("#introducing-the-selenium-webdriver-api-by-example > .toggler-python")).click()
    await driver.findElement(By.css("#introducing-the-selenium-webdriver-api-by-example > .highlight-python pre")).click()
    await driver.findElement(By.id("container")).click()
    await driver.findElement(By.id("introducing-the-selenium-webdriver-api-by-example")).click()
    await driver.findElement(By.linkText("Support")).click()
    await driver.close()
  })
})
