# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()
vars = {}
# Test name: YahooNew
# Step # | name | target | value | comment
# 1 | open | https://login.yahoo.com/?.src=ym&.lang=en-US&.intl=us&.done=https%3A%2F%2Fmail.yahoo.com%2Fd |  | 
driver.get("https://login.yahoo.com/?.src=ym&.lang=en-US&.intl=us&.done=https%3A%2F%2Fmail.yahoo.com%2Fd")
# 2 | setWindowSize | 1366x728 |  | 
driver.set_window_size(1366, 728)
# 3 | type | id=login-username | mkalil@yahoo.com | 
driver.find_element(By.ID, "login-username").send_keys("mkalil@yahoo.com")
# 4 | click | css=label:nth-child(2) |  | 
driver.find_element(By.CSS_SELECTOR, "label:nth-child(2)").click()
# 5 | click | id=login-signin |  | 
driver.find_element(By.ID, "login-signin").click()
# 6 | type | id=login-passwd | Nas1Fas! |
driver.find_element(By.ID, "login-passwd").send_keys("Nas1Fas!")
# 7 | click | id=login-signin |  | 
driver.find_element(By.ID, "login-signin").click()
# 8 | close |  |  | 
driver.close()
driver.quit()
  
