# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()
vars = {}
  
# Test name: LoginExample
# Step # | name | target | value | comment
# 1 | open | http://the-internet.herokuapp.com/ |  | 
driver.get("http://the-internet.herokuapp.com/")
# 2 | setWindowSize | 1366x728 |  | 
driver.set_window_size(1366, 728)
# 3 | click | linkText=Form Authentication |  | 
driver.find_element(By.LINK_TEXT, "Form Authentication").click()
# 4 | click | id=username |  | 
driver.find_element(By.ID, "username").click()
# 5 | click | css=html |  | 
driver.find_element(By.CSS_SELECTOR, "html").click()
# 6 | click | id=username |  | 
driver.find_element(By.ID, "username").click()
# 7 | click | id=username |  | 
driver.find_element(By.ID, "username").click()
# 8 | doubleClick | id=username |  | 
element = self.driver.find_element(By.ID, "username")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 9 | click | id=username |  | 
driver.find_element(By.ID, "username").click()
# 10 | click | css=.fa |  | 
driver.find_element(By.CSS_SELECTOR, ".fa").click()
# 11 | click | id=flash |  | 
driver.find_element(By.ID, "flash").click()
# 12 | verifyText | id=flash | You logged into a secure area!\n× | 
assert self.driver.find_element(By.ID, "flash").text == "You logged into a secure area!\\\\n×"
# 13 | click | css=.example |  | 
driver.find_element(By.CSS_SELECTOR, ".example").click()
# 14 | click | css=.icon-2x |  | 
driver.find_element(By.CSS_SELECTOR, ".icon-2x").click()
# 15 | click | id=flash |  | 
driver.find_element(By.ID, "flash").click()
# 16 | verifyText | id=flash | You logged out of the secure area!\n× | 
assert self.driver.find_element(By.ID, "flash").text == "You logged out of the secure area!\\\\n×"
# 17 | click | id=content |  | 
driver.find_element(By.ID, "content").click()
# 18 | close |  |  | 
driver.close()
driver.quit()
  
