# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestPHPTRAVELS():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_pHPTRAVELS(self):
    # Test name: PHPTRAVELS
    # Step # | name | target | value | comment
    # 1 | open | /demo/ |  | 
    self.driver.get("https://phptravels.com/demo/")
    # 2 | setWindowSize | 1050x708 |  | 
    self.driver.set_window_size(1050, 708)
    # 3 | runScript | window.scrollTo(0,602) |  | 
    self.driver.execute_script("window.scrollTo(0,602)")
    # 4 | click | css=.wow:nth-child(2) small:nth-child(1) |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 5 | selectWindow | handle=${win7803} |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".wow:nth-child(2) small:nth-child(1)").click()
    # 6 | click | css=.nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle |  | 
    self.vars["win7803"] = self.wait_for_window(2000)
    # 7 | mouseOver | css=.nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle |  | 
    self.driver.switch_to.window(self.vars["win7803"])
    # 8 | mouseOut | css=.open > .dropdown-toggle |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle").click()
    # 9 | click | linkText=Logout |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 10 | mouseOver | linkText=Logout |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | type | name=username | user@phptravels.com | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 12 | type | name=password | demouser | 
    element = self.driver.find_element(By.LINK_TEXT, "Logout")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 13 | click | id=remember-me |  | 
    self.driver.find_element(By.NAME, "username").send_keys("user@phptravels.com")
    # 14 | click | id=cookieconsent:desc |  | 
    self.driver.find_element(By.NAME, "password").send_keys("demouser")
    # 15 | click | id=cookyGotItBtn |  | 
    self.driver.find_element(By.ID, "remember-me").click()
    # 16 | mouseOver | id=cookyGotItBtn |  | 
    self.driver.find_element(By.ID, "cookieconsent:desc").click()
    # 17 | mouseOut | id=cookyGotItBtn |  | 
    self.driver.find_element(By.ID, "cookyGotItBtn").click()
    # 18 | click | css=.btn-action |  | 
    element = self.driver.find_element(By.ID, "cookyGotItBtn")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 19 | mouseOver | css=.btn-action |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 20 | click | css=.nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-action").click()
    # 21 | mouseOver | css=.nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-action")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 22 | mouseOut | css=.open > .dropdown-toggle |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle").click()
    # 23 | click | linkText=Account |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".nav:nth-child(1) > li:nth-child(1) > .dropdown-toggle")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 24 | mouseOver | linkText=Account |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 25 | click | linkText=My Profile |  | 
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    # 26 | mouseOver | linkText=My Profile |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Account")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 27 | runScript | window.scrollTo(0,104) |  | 
    self.driver.find_element(By.LINK_TEXT, "My Profile").click()
    # 28 | mouseOut | linkText=My Profile |  | 
    element = self.driver.find_element(By.LINK_TEXT, "My Profile")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 29 | click | linkText=Wishlist |  | 
    self.driver.execute_script("window.scrollTo(0,104)")
    # 30 | mouseOver | linkText=Wishlist |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 31 | runScript | window.scrollTo(0,137) |  | 
    self.driver.find_element(By.LINK_TEXT, "Wishlist").click()
    # 32 | runScript | window.scrollTo(0,326) |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Wishlist")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 33 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,137)")
    # 34 | runScript | window.scrollTo(0,285) |  | 
    self.driver.execute_script("window.scrollTo(0,326)")
    # 35 | runScript | window.scrollTo(0,41) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 36 | mouseOut | linkText=Wishlist |  | 
    self.driver.execute_script("window.scrollTo(0,285)")
    # 37 | click | css=.fa-hotel |  | 
    self.driver.execute_script("window.scrollTo(0,41)")
    # 38 | mouseOver | css=.fa-hotel |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 39 | click | css=.col-md-3:nth-child(1) > #tour-36 img |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-hotel").click()
    # 40 | runScript | window.scrollTo(0,780) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".fa-hotel")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 41 | runScript | window.scrollTo(0,184) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(1) > #tour-36 img").click()
    # 42 | click | css=.fotorama__arr--next |  | 
    self.driver.execute_script("window.scrollTo(0,780)")
    # 43 | selectFrame | index=0 |  | 
    self.driver.execute_script("window.scrollTo(0,184)")
    # 44 | click | css=div:nth-child(3) > div:nth-child(3) > img |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fotorama__arr--next").click()
    # 45 | click | css=div:nth-child(3) > div:nth-child(1) > img |  | 
    self.driver.switch_to.frame(0)
    # 46 | click | css=div:nth-child(3) > div:nth-child(5) > img |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > div:nth-child(3) > img").click()
    # 47 | click | css=div:nth-child(3) > div:nth-child(2) > img |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > div:nth-child(1) > img").click()
    # 48 | click | css=div:nth-child(3) > div:nth-child(2) > img |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > div:nth-child(5) > img").click()
    # 49 | click | css=.gm-style > div > div:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > div:nth-child(2) > img").click()
    # 50 | click | css=div:nth-child(3) > div:nth-child(4) > img |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > div:nth-child(2) > img").click()
    # 51 | click | css=.gm-style > div > div:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".gm-style > div > div:nth-child(3)").click()
    # 52 | click | css=.gm-style-mtc:nth-child(2) > div:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > div:nth-child(4) > img").click()
    # 53 | selectFrame | relative=parent |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".gm-style > div > div:nth-child(3)").click()
    # 54 | click | name=date |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".gm-style-mtc:nth-child(2) > div:nth-child(1)").click()
    # 55 | click | css=tr:nth-child(4) > .day:nth-child(4) |  | 
    self.driver.switch_to.default_content()
    # 56 | click | id=selectedAdults |  | 
    self.driver.find_element(By.NAME, "date").click()
    # 57 | select | id=selectedAdults | label=2 | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > .day:nth-child(4)").click()
    # 58 | click | id=selectedAdults |  | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 59 | click | id=selectedChild |  | 
    dropdown = self.driver.find_element(By.ID, "selectedAdults")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    # 60 | select | id=selectedChild | label=2 | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 61 | click | id=selectedChild |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 62 | click | css=.btn-action |  | 
    dropdown = self.driver.find_element(By.ID, "selectedChild")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    # 63 | mouseOver | css=.btn-action |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 64 | click | css=tr:nth-child(1) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-action").click()
    # 65 | click | css=tr:nth-child(2) span > span:nth-child(2) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-action")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 66 | click | css=tr:nth-child(3) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) span > span:nth-child(2)").click()
    # 67 | click | css=tr:nth-child(4) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span > span:nth-child(2)").click()
    # 68 | click | css=.coupon |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) span > span:nth-child(2)").click()
    # 69 | type | css=.coupon | PROMO | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) span > span:nth-child(2)").click()
    # 70 | click | css=.applycoupon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".coupon").click()
    # 71 | assertAlert | Invalid Coupon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".coupon").send_keys("PROMO")
    # 72 | click | css=.form-horizontal |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".applycoupon").click()
    # 73 | click | name=passport[1][name] |  | 
    assert self.driver.switch_to.alert.text == "Invalid Coupon"
    # 74 | type | name=passport[1][name] | USER1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-horizontal").click()
    # 75 | type | name=passport[1][passportnumber] | 1234567890 | 
    self.driver.find_element(By.NAME, "passport[1][name]").click()
    # 76 | click | name=passport[1][age] |  | 
    self.driver.find_element(By.NAME, "passport[1][name]").send_keys("USER1")
    # 77 | type | name=passport[1][age] | 45 | 
    self.driver.find_element(By.NAME, "passport[1][passportnumber]").send_keys("1234567890")
    # 78 | click | name=passport[2][name] |  | 
    self.driver.find_element(By.NAME, "passport[1][age]").click()
    # 79 | type | name=passport[2][name] | USER2 | 
    self.driver.find_element(By.NAME, "passport[1][age]").send_keys("45")
    # 80 | click | name=passport[2][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[2][name]").click()
    # 81 | type | name=passport[2][passportnumber] | 2345678901 | 
    self.driver.find_element(By.NAME, "passport[2][name]").send_keys("USER2")
    # 82 | click | name=passport[2][age] |  | 
    self.driver.find_element(By.NAME, "passport[2][passportnumber]").click()
    # 83 | type | name=passport[2][age] | 39 | 
    self.driver.find_element(By.NAME, "passport[2][passportnumber]").send_keys("2345678901")
    # 84 | click | name=passport[3][name] |  | 
    self.driver.find_element(By.NAME, "passport[2][age]").click()
    # 85 | type | name=passport[3][name] | USER3 | 
    self.driver.find_element(By.NAME, "passport[2][age]").send_keys("39")
    # 86 | click | name=passport[3][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[3][name]").click()
    # 87 | type | name=passport[3][passportnumber] | 3456789012 | 
    self.driver.find_element(By.NAME, "passport[3][name]").send_keys("USER3")
    # 88 | click | name=passport[3][age] |  | 
    self.driver.find_element(By.NAME, "passport[3][passportnumber]").click()
    # 89 | type | name=passport[3][age] | 15 | 
    self.driver.find_element(By.NAME, "passport[3][passportnumber]").send_keys("3456789012")
    # 90 | click | name=passport[4][name] |  | 
    self.driver.find_element(By.NAME, "passport[3][age]").click()
    # 91 | type | name=passport[4][name] | USER4 | 
    self.driver.find_element(By.NAME, "passport[3][age]").send_keys("15")
    # 92 | click | name=passport[4][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[4][name]").click()
    # 93 | type | name=passport[4][passportnumber] | 4567890123 | 
    self.driver.find_element(By.NAME, "passport[4][name]").send_keys("USER4")
    # 94 | click | name=passport[4][age] |  | 
    self.driver.find_element(By.NAME, "passport[4][passportnumber]").click()
    # 95 | type | name=passport[4][age] | 8 | 
    self.driver.find_element(By.NAME, "passport[4][passportnumber]").send_keys("4567890123")
    # 96 | click | name=logged |  | 
    self.driver.find_element(By.NAME, "passport[4][age]").click()
    # 97 | mouseOver | name=logged |  | 
    self.driver.find_element(By.NAME, "passport[4][age]").send_keys("8")
    # 98 | runScript | window.scrollTo(0,431) |  | 
    self.driver.find_element(By.NAME, "logged").click()
    # 99 | runScript | window.scrollTo(0,638) |  | 
    element = self.driver.find_element(By.NAME, "logged")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 100 | runScript | window.scrollTo(0,743) |  | 
    self.driver.execute_script("window.scrollTo(0,431)")
    # 101 | runScript | window.scrollTo(0,28) |  | 
    self.driver.execute_script("window.scrollTo(0,638)")
    # 102 | click | css=.btn-primary:nth-child(2) |  | 
    self.driver.execute_script("window.scrollTo(0,743)")
    # 103 | mouseOver | css=.btn-primary:nth-child(2) |  | 
    self.driver.execute_script("window.scrollTo(0,28)")
    # 104 | mouseOut | css=.btn-primary:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
    # 105 | click | id=gateway |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 106 | select | id=gateway | label=Bank Transfer | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 107 | click | id=gateway |  | 
    self.driver.find_element(By.ID, "gateway").click()
    # 108 | runScript | window.scrollTo(0,268) |  | 
    dropdown = self.driver.find_element(By.ID, "gateway")
    dropdown.find_element(By.XPATH, "//option[. = 'Bank Transfer']").click()
    # 109 | runScript | window.scrollTo(0,378) |  | 
    self.driver.find_element(By.ID, "gateway").click()
    # 110 | runScript | window.scrollTo(0,963) |  | 
    self.driver.execute_script("window.scrollTo(0,268)")
    # 111 | runScript | window.scrollTo(0,898) |  | 
    self.driver.execute_script("window.scrollTo(0,378)")
    # 112 | runScript | window.scrollTo(0,478) |  | 
    self.driver.execute_script("window.scrollTo(0,963)")
    # 113 | runScript | window.scrollTo(0,116) |  | 
    self.driver.execute_script("window.scrollTo(0,898)")
    # 114 | click | css=#invoiceTable > tbody > tr:nth-child(1) div |  | 
    self.driver.execute_script("window.scrollTo(0,478)")
    # 115 | click | id=gateway |  | 
    self.driver.execute_script("window.scrollTo(0,116)")
    # 116 | select | id=gateway | label=Stripe Credit Card | 
    self.driver.find_element(By.CSS_SELECTOR, "#invoiceTable > tbody > tr:nth-child(1) div").click()
    # 117 | click | id=gateway |  | 
    self.driver.find_element(By.ID, "gateway").click()
    # 118 | click | id=card-holder-firstname |  | 
    dropdown = self.driver.find_element(By.ID, "gateway")
    dropdown.find_element(By.XPATH, "//option[. = 'Stripe Credit Card']").click()
    # 119 | type | id=card-holder-firstname | USER | 
    self.driver.find_element(By.ID, "gateway").click()
    # 120 | click | id=card-holder-lastname |  | 
    self.driver.find_element(By.ID, "card-holder-firstname").click()
    # 121 | type | id=card-holder-lastname | ONE | 
    self.driver.find_element(By.ID, "card-holder-firstname").send_keys("USER")
    # 122 | click | id=card-number |  | 
    self.driver.find_element(By.ID, "card-holder-lastname").click()
    # 123 | type | id=card-number | 1234 | 
    self.driver.find_element(By.ID, "card-holder-lastname").send_keys("ONE")
    # 124 | type | id=card-number | 1234567890123456 | 
    self.driver.find_element(By.ID, "card-number").click()
    # 125 | click | id=expiry-month |  | 
    self.driver.find_element(By.ID, "card-number").send_keys("1234")
    # 126 | select | id=expiry-month | label=Oct (10) | 
    self.driver.find_element(By.ID, "card-number").send_keys("1234567890123456")
    # 127 | click | id=expiry-month |  | 
    self.driver.find_element(By.ID, "expiry-month").click()
    # 128 | click | id=expiry-year |  | 
    dropdown = self.driver.find_element(By.ID, "expiry-month")
    dropdown.find_element(By.XPATH, "//option[. = 'Oct (10)']").click()
    # 129 | select | id=expiry-year | label=2028 | 
    self.driver.find_element(By.ID, "expiry-month").click()
    # 130 | click | id=expiry-year |  | 
    self.driver.find_element(By.ID, "expiry-year").click()
    # 131 | click | id=cvv |  | 
    dropdown = self.driver.find_element(By.ID, "expiry-year")
    dropdown.find_element(By.XPATH, "//option[. = '2028']").click()
    # 132 | type | id=cvv | 123 | 
    self.driver.find_element(By.ID, "expiry-year").click()
    # 133 | click | css=.btn-lg |  | 
    self.driver.find_element(By.ID, "cvv").click()
    # 134 | mouseOver | css=.btn-lg |  | 
    self.driver.find_element(By.ID, "cvv").send_keys("123")
    # 135 | runScript | window.scrollTo(0,432) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg").click()
    # 136 | runScript | window.scrollTo(0,688) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-lg")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 137 | runScript | window.scrollTo(0,426) |  | 
    self.driver.execute_script("window.scrollTo(0,432)")
    # 138 | click | id=8 |  | 
    self.driver.execute_script("window.scrollTo(0,688)")
    # 139 | chooseOkOnNextConfirmation |  |  | 
    self.driver.execute_script("window.scrollTo(0,426)")
    # 140 | mouseOver | id=8 |  | 
    self.driver.find_element(By.ID, "8").click()
    # 141 | assertConfirmation | Are you sure you want to pay at arrival? |  | 
    # 142 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    element = self.driver.find_element(By.ID, "8")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 143 | click | id=btn |  | 
    assert self.driver.switch_to.alert.text == "Are you sure you want to pay at arrival?"
    # 144 | mouseOver | id=btn |  | 
    self.driver.switch_to.alert.accept()
    # 145 | mouseOut | id=btn |  | 
    self.driver.find_element(By.ID, "btn").click()
    # 146 | click | css=.img-responsive:nth-child(1) |  | 
    element = self.driver.find_element(By.ID, "btn")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 147 | click | id=downloadInvoice |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 148 | mouseOver | id=downloadInvoice |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".img-responsive:nth-child(1)").click()
    # 149 | mouseOut | id=downloadInvoice |  | 
    self.driver.find_element(By.ID, "downloadInvoice").click()
    # 150 | click | css=.text-center:nth-child(3) > .text-center |  | 
    element = self.driver.find_element(By.ID, "downloadInvoice")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 151 | mouseOver | css=.text-center:nth-child(3) > .text-center |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 152 | mouseOver | css=#s2id_autogen3 .select2-chosen |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) > .text-center").click()
    # 153 | mouseOut | css=#s2id_autogen3 .select2-chosen |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) > .text-center")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 154 | mouseDown | css=#s2id_autogen3 .select2-chosen |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#s2id_autogen3 .select2-chosen")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 155 | mouseUp | css=.select2-focused |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 156 | click | css=body |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#s2id_autogen3 .select2-chosen")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 157 | click | id=tourtype |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".select2-focused")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 158 | select | id=tourtype | label=Private | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 159 | click | id=tourtype |  | 
    self.driver.find_element(By.ID, "tourtype").click()
    # 160 | click | css=.col-md-2:nth-child(5) > .btn-primary:nth-child(2) |  | 
    dropdown = self.driver.find_element(By.ID, "tourtype")
    dropdown.find_element(By.XPATH, "//option[. = 'Private']").click()
    # 161 | mouseOver | css=.col-md-2:nth-child(5) > .btn-primary:nth-child(2) |  | 
    self.driver.find_element(By.ID, "tourtype").click()
    # 162 | click | name=date |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-2:nth-child(5) > .btn-primary:nth-child(2)").click()
    # 163 | click | css=tr:nth-child(4) > .day:nth-child(4) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-md-2:nth-child(5) > .btn-primary:nth-child(2)")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 164 | click | id=selectedAdults |  | 
    self.driver.find_element(By.NAME, "date").click()
    # 165 | click | id=selectedAdults |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > .day:nth-child(4)").click()
    # 166 | click | id=selectedAdults |  | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 167 | select | id=selectedAdults | label=3 | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 168 | click | id=selectedAdults |  | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 169 | click | id=selectedChild |  | 
    dropdown = self.driver.find_element(By.ID, "selectedAdults")
    dropdown.find_element(By.XPATH, "//option[. = '3']").click()
    # 170 | select | id=selectedChild | label=1 | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 171 | click | id=selectedChild |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 172 | click | css=.btn-action |  | 
    dropdown = self.driver.find_element(By.ID, "selectedChild")
    dropdown.find_element(By.XPATH, "//option[. = '1']").click()
    # 173 | mouseOver | css=.btn-action |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 174 | click | css=tr:nth-child(1) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-action").click()
    # 175 | click | css=tr:nth-child(2) span > span:nth-child(2) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-action")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 176 | click | css=tr:nth-child(3) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) span > span:nth-child(2)").click()
    # 177 | click | css=tr:nth-child(4) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span > span:nth-child(2)").click()
    # 178 | click | name=passport[1][name] |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) span > span:nth-child(2)").click()
    # 179 | type | name=passport[1][name] | USER1 | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) span > span:nth-child(2)").click()
    # 180 | click | name=passport[1][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[1][name]").click()
    # 181 | type | name=passport[1][passportnumber] | 1234567890 | 
    self.driver.find_element(By.NAME, "passport[1][name]").send_keys("USER1")
    # 182 | click | name=passport[1][age] |  | 
    self.driver.find_element(By.NAME, "passport[1][passportnumber]").click()
    # 183 | type | name=passport[1][age] | 45 | 
    self.driver.find_element(By.NAME, "passport[1][passportnumber]").send_keys("1234567890")
    # 184 | click | name=passport[2][name] |  | 
    self.driver.find_element(By.NAME, "passport[1][age]").click()
    # 185 | type | name=passport[2][name] | USER2 | 
    self.driver.find_element(By.NAME, "passport[1][age]").send_keys("45")
    # 186 | click | name=passport[2][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[2][name]").click()
    # 187 | type | name=passport[2][passportnumber] | 2345678901 | 
    self.driver.find_element(By.NAME, "passport[2][name]").send_keys("USER2")
    # 188 | click | name=passport[2][age] |  | 
    self.driver.find_element(By.NAME, "passport[2][passportnumber]").click()
    # 189 | type | name=passport[2][age] | 39 | 
    self.driver.find_element(By.NAME, "passport[2][passportnumber]").send_keys("2345678901")
    # 190 | click | name=passport[3][name] |  | 
    self.driver.find_element(By.NAME, "passport[2][age]").click()
    # 191 | type | name=passport[3][name] | USER3 | 
    self.driver.find_element(By.NAME, "passport[2][age]").send_keys("39")
    # 192 | click | name=passport[3][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[3][name]").click()
    # 193 | type | name=passport[3][passportnumber] | 3456789012 | 
    self.driver.find_element(By.NAME, "passport[3][name]").send_keys("USER3")
    # 194 | click | name=passport[3][age] |  | 
    self.driver.find_element(By.NAME, "passport[3][passportnumber]").click()
    # 195 | type | name=passport[3][age] | 15 | 
    self.driver.find_element(By.NAME, "passport[3][passportnumber]").send_keys("3456789012")
    # 196 | click | name=passport[4][name] |  | 
    self.driver.find_element(By.NAME, "passport[3][age]").click()
    # 197 | type | name=passport[4][name] | USER4 | 
    self.driver.find_element(By.NAME, "passport[3][age]").send_keys("15")
    # 198 | click | name=passport[4][passportnumber] |  | 
    self.driver.find_element(By.NAME, "passport[4][name]").click()
    # 199 | type | name=passport[4][passportnumber] | 4567890123 | 
    self.driver.find_element(By.NAME, "passport[4][name]").send_keys("USER4")
    # 200 | click | name=passport[4][age] |  | 
    self.driver.find_element(By.NAME, "passport[4][passportnumber]").click()
    # 201 | type | name=passport[4][age] | 8 | 
    self.driver.find_element(By.NAME, "passport[4][passportnumber]").send_keys("4567890123")
    # 202 | click | name=logged |  | 
    self.driver.find_element(By.NAME, "passport[4][age]").click()
    # 203 | runScript | window.scrollTo(0,1439) |  | 
    self.driver.find_element(By.NAME, "passport[4][age]").send_keys("8")
    # 204 | runScript | window.scrollTo(0,673) |  | 
    self.driver.find_element(By.NAME, "logged").click()
    # 205 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,1439)")
    # 206 | click | id=8 |  | 
    self.driver.execute_script("window.scrollTo(0,673)")
    # 207 | chooseOkOnNextConfirmation |  |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 208 | mouseOver | id=8 |  | 
    self.driver.find_element(By.ID, "8").click()
    # 209 | assertConfirmation | Are you sure you want to pay at arrival? |  | 
    # 210 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    element = self.driver.find_element(By.ID, "8")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 211 | click | css=.text-center:nth-child(2) > .text-center |  | 
    assert self.driver.switch_to.alert.text == "Are you sure you want to pay at arrival?"
    # 212 | mouseOver | css=.text-center:nth-child(2) > .text-center |  | 
    self.driver.switch_to.alert.accept()
    # 213 | click | css=.go-right:nth-child(2) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(2) > .text-center").click()
    # 214 | mouseOver | css=.go-right:nth-child(2) > a |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(2) > .text-center")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 215 | click | css=.col-md-6:nth-child(1) > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".go-right:nth-child(2) > a").click()
    # 216 | mouseOver | css=.col-md-6:nth-child(1) > .btn |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".go-right:nth-child(2) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 217 | click | css=.visible-lg > p:nth-child(5) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(1) > .btn").click()
    # 218 | click | css=.visible-lg > p:nth-child(5) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(1) > .btn")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 219 | click | css=.panel |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".visible-lg > p:nth-child(5)").click()
    # 220 | click | css=.desc-scrol |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".visible-lg > p:nth-child(5)").click()
    # 221 | doubleClick | css=.desc-scrol |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel").click()
    # 222 | click | css=.desc-scrol |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".desc-scrol").click()
    # 223 | click | css=.desc-scrol |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".desc-scrol")
    actions = ActionChains(driver)
    actions.double_click(element).perform()
    # 224 | click | css=.text-center:nth-child(3) > .text-center |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".desc-scrol").click()
    # 225 | mouseOver | css=.text-center:nth-child(3) > .text-center |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".desc-scrol").click()
    # 226 | mouseOut | css=.text-center:nth-child(3) > .text-center |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) > .text-center").click()
    # 227 | click | css=.col-md-3:nth-child(4) > #tour-36 img |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) > .text-center")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 228 | mouseOver | css=.col-md-3:nth-child(4) > #tour-36 img |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 229 | runScript | window.scrollTo(0,1222) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(4) > #tour-36 img").click()
    # 230 | click | id=selectedAdults |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(4) > #tour-36 img")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 231 | select | id=selectedAdults | label=5 | 
    self.driver.execute_script("window.scrollTo(0,1222)")
    # 232 | click | id=selectedAdults |  | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 233 | click | id=selectedChild |  | 
    dropdown = self.driver.find_element(By.ID, "selectedAdults")
    dropdown.find_element(By.XPATH, "//option[. = '5']").click()
    # 234 | select | id=selectedChild | label=3 | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 235 | click | id=selectedChild |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 236 | click | id=selectedInfants |  | 
    dropdown = self.driver.find_element(By.ID, "selectedChild")
    dropdown.find_element(By.XPATH, "//option[. = '3']").click()
    # 237 | select | id=selectedInfants | label=2 | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 238 | click | id=selectedInfants |  | 
    self.driver.find_element(By.ID, "selectedInfants").click()
    # 239 | click | css=.loader:nth-child(2) |  | 
    dropdown = self.driver.find_element(By.ID, "selectedInfants")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    # 240 | mouseOver | css=.loader:nth-child(2) |  | 
    self.driver.find_element(By.ID, "selectedInfants").click()
    # 241 | click | css=.loader:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".loader:nth-child(2)").click()
    # 242 | click | id=selectedAdults |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".loader:nth-child(2)")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 243 | select | id=selectedAdults | label=3 | 
    self.driver.find_element(By.CSS_SELECTOR, ".loader:nth-child(2)").click()
    # 244 | click | id=selectedAdults |  | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 245 | click | id=selectedChild |  | 
    dropdown = self.driver.find_element(By.ID, "selectedAdults")
    dropdown.find_element(By.XPATH, "//option[. = '3']").click()
    # 246 | select | id=selectedChild | label=2 | 
    self.driver.find_element(By.ID, "selectedAdults").click()
    # 247 | click | id=selectedChild |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 248 | click | css=.btn-action |  | 
    dropdown = self.driver.find_element(By.ID, "selectedChild")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    # 249 | mouseOver | css=.btn-action |  | 
    self.driver.find_element(By.ID, "selectedChild").click()
    # 250 | click | css=tr:nth-child(1) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-action").click()
    # 251 | click | css=tr:nth-child(2) span > span:nth-child(2) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-action")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 252 | click | css=tr:nth-child(3) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) span > span:nth-child(2)").click()
    # 253 | click | css=tr:nth-child(4) span > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span > span:nth-child(2)").click()
    # 254 | click | name=logged |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) span > span:nth-child(2)").click()
    # 255 | runScript | window.scrollTo(0,1635) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) span > span:nth-child(2)").click()
    # 256 | runScript | window.scrollTo(0,263) |  | 
    self.driver.find_element(By.NAME, "logged").click()
    # 257 | runScript | window.scrollTo(0,593) |  | 
    self.driver.execute_script("window.scrollTo(0,1635)")
    # 258 | runScript | window.scrollTo(0,418) |  | 
    self.driver.execute_script("window.scrollTo(0,263)")
    # 259 | click | id=10 |  | 
    self.driver.execute_script("window.scrollTo(0,593)")
    # 260 | chooseOkOnNextConfirmation |  |  | 
    self.driver.execute_script("window.scrollTo(0,418)")
    # 261 | mouseOver | id=10 |  | 
    self.driver.find_element(By.ID, "10").click()
    # 262 | assertConfirmation | Êtes-vous sûr de vouloir payer à l'arrivée? |  | 
    # 263 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    element = self.driver.find_element(By.ID, "10")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 264 | click | css=tr:nth-child(2) tr:nth-child(2) > td:nth-child(1) |  | 
    assert self.driver.switch_to.alert.text == "Êtes-vous sûr de vouloir payer à l\'arrivée?"
    # 265 | verifyText | css=div:nth-child(1) > table > tbody > tr > td > div:nth-child(3) | FACTURE | 
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) tr:nth-child(2) > td:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > table > tbody > tr > td > div:nth-child(3)").text == "FACTURE"
  
