# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestDemo():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo(self):
    # Test name: demo
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://demo.applitools.com/")
    # 2 | setWindowSize | 1050x708 |  | 
    self.driver.set_window_size(1050, 708)
    # 3 | verifyText | css=.auth-header | Login Form | 
    assert self.driver.find_element(By.CSS_SELECTOR, ".auth-header").text == "Login Form"
    # 4 | click | id=username |  | 
    self.driver.find_element(By.ID, "username").click()
    # 5 | type | id=username | demo | 
    self.driver.find_element(By.ID, "username").send_keys("demo")
    # 6 | type | id=password | demo | 
    self.driver.find_element(By.ID, "password").send_keys("demo")
    # 7 | click | id=log-in |  | 
    self.driver.find_element(By.ID, "log-in").click()
    # 8 | assertTitle | ACME demo app |  | 
    assert self.driver.title == "ACME demo app"
    # 9 | close |  |  | 
    self.driver.close()
  
