# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSeleniumDemoTestSite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_seleniumDemoTestSite(self):
    # Test name: SeleniumDemoTestSite
    # Step # | name | target | value | comment
    # 1 | open | https://www.seleniumeasy.com/test/ |  | 
    self.driver.get("https://www.seleniumeasy.com/test/")
    # 2 | setWindowSize | 1382x744 |  | 
    self.driver.set_window_size(1382, 744)
    # 3 | verifyTitle | Selenium Easy - Best Demo website to practice Selenium Webdriver Online |  | 
    assert self.driver.title == "Selenium Easy - Best Demo website to practice Selenium Webdriver Online"
    # 4 | assertTitle | Selenium Easy - Best Demo website to practice Selenium Webdriver Online |  | 
    assert self.driver.title == "Selenium Easy - Best Demo website to practice Selenium Webdriver Online"
    # 5 | assertText | id=navbar-brand-centered | Input Forms\nDate pickers\nTable\nProgress Bars\nAlerts & Modals\nList Box\nOthers | 
    assert self.driver.find_element(By.ID, "navbar-brand-centered").text == "Input Forms\nDate pickers\nTable\nProgress Bars\nAlerts & Modals\nList Box\nOthers"
    # 6 | mouseOver | css=.glyphicon-home |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-home")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=.glyphicon-home |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | mouseDownAt | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right | 9,6 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(1) > .glyphicon-chevron-right")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 9 | mouseMoveAt | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right | 9,6 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(1) > .glyphicon-chevron-right")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 10 | mouseUpAt | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right | 9,6 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(1) > .glyphicon-chevron-right")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 11 | click | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(1) > .glyphicon-chevron-right").click()
    # 12 | mouseDownAt | linkText=Simple Form Demo | 53,10 | 
    element = self.driver.find_element(By.LINK_TEXT, "Simple Form Demo")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 13 | mouseMoveAt | linkText=Simple Form Demo | 53,10 | 
    element = self.driver.find_element(By.LINK_TEXT, "Simple Form Demo")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 14 | mouseUpAt | linkText=Simple Form Demo | 53,10 | 
    element = self.driver.find_element(By.LINK_TEXT, "Simple Form Demo")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 15 | click | linkText=Simple Form Demo |  | 
    self.driver.find_element(By.LINK_TEXT, "Simple Form Demo").click()
    # 16 | click | id=user-message |  | 
    self.driver.find_element(By.ID, "user-message").click()
    # 17 | click | id=user-message |  | 
    self.driver.find_element(By.ID, "user-message").click()
    # 18 | type | id=user-message | Testing Selenium Demo | 
    self.driver.find_element(By.ID, "user-message").send_keys("Testing Selenium Demo")
    # 19 | click | css=.btn:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 20 | click | id=sum1 |  | 
    self.driver.find_element(By.ID, "sum1").click()
    # 21 | type | id=sum1 | 100 | 
    self.driver.find_element(By.ID, "sum1").send_keys("100")
    # 22 | click | id=sum2 |  | 
    self.driver.find_element(By.ID, "sum2").click()
    # 23 | type | id=sum2 | 200 | 
    self.driver.find_element(By.ID, "sum2").send_keys("200")
    # 24 | click | css=.btn:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    # 25 | click | css=.tree-branch:nth-child(1) > .glyphicon-chevron-right |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(1) > .glyphicon-chevron-right").click()
    # 26 | click | linkText=Checkbox Demo |  | 
    self.driver.find_element(By.LINK_TEXT, "Checkbox Demo").click()
    # 27 | click | id=isAgeSelected |  | 
    self.driver.find_element(By.ID, "isAgeSelected").click()
    # 28 | click | css=.checkbox:nth-child(3) .cb1-element |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(3) .cb1-element").click()
    # 29 | click | css=.checkbox:nth-child(5) .cb1-element |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(5) .cb1-element").click()
    # 30 | click | id=check1 |  | 
    self.driver.find_element(By.ID, "check1").click()
    # 31 | click | id=check1 |  | 
    self.driver.find_element(By.ID, "check1").click()
    # 32 | click | css=.checkbox:nth-child(3) .cb1-element |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(3) .cb1-element").click()
    # 33 | click | css=.checkbox:nth-child(5) .cb1-element |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(5) .cb1-element").click()
    # 34 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(3) > .tree-branch:nth-child(1) > a").click()
    # 35 | click | linkText=Radio Buttons Demo |  | 
    self.driver.find_element(By.LINK_TEXT, "Radio Buttons Demo").click()
    # 36 | click | css=.panel-body > .radio-inline:nth-child(3) > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel-body > .radio-inline:nth-child(3) > input").click()
    # 37 | click | id=buttoncheck |  | 
    self.driver.find_element(By.ID, "buttoncheck").click()
    # 38 | click | name=optradio |  | 
    self.driver.find_element(By.NAME, "optradio").click()
    # 39 | click | id=buttoncheck |  | 
    self.driver.find_element(By.ID, "buttoncheck").click()
    # 40 | click | css=.panel:nth-child(5) > .panel-body |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(5) > .panel-body").click()
    # 41 | click | name=gender |  | 
    self.driver.find_element(By.NAME, "gender").click()
    # 42 | click | css=.radio-inline:nth-child(4) > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".radio-inline:nth-child(4) > input").click()
    # 43 | click | css=.btn:nth-child(5) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    # 44 | click | css=.panel-body > div:nth-child(2) > .radio-inline:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel-body > div:nth-child(2) > .radio-inline:nth-child(3)").click()
    # 45 | click | css=div:nth-child(3) > .radio-inline:nth-child(3) > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .radio-inline:nth-child(3) > input").click()
    # 46 | click | css=.btn:nth-child(5) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    # 47 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(3) > .tree-branch:nth-child(1) > a").click()
    # 48 | click | linkText=Radio Buttons Demo |  | 
    self.driver.find_element(By.LINK_TEXT, "Radio Buttons Demo").click()
    # 49 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(3) > .tree-branch:nth-child(1) > a").click()
    # 50 | click | linkText=Select Dropdown List |  | 
    self.driver.find_element(By.LINK_TEXT, "Select Dropdown List").click()
    # 51 | click | id=select-demo |  | 
    self.driver.find_element(By.ID, "select-demo").click()
    # 52 | select | id=select-demo | label=Tuesday | 
    dropdown = self.driver.find_element(By.ID, "select-demo")
    dropdown.find_element(By.XPATH, "//option[. = 'Tuesday']").click()
    # 53 | click | id=select-demo |  | 
    self.driver.find_element(By.ID, "select-demo").click()
    # 54 | click | id=select-demo |  | 
    self.driver.find_element(By.ID, "select-demo").click()
    # 55 | select | id=select-demo | label=Friday | 
    dropdown = self.driver.find_element(By.ID, "select-demo")
    dropdown.find_element(By.XPATH, "//option[. = 'Friday']").click()
    # 56 | click | id=select-demo |  | 
    self.driver.find_element(By.ID, "select-demo").click()
    # 57 | addSelection | id=multi-select | label=New Jersey | 
    dropdown = self.driver.find_element(By.ID, "multi-select")
    dropdown.find_element(By.XPATH, "//option[. = 'New Jersey']").click()
    # 58 | addSelection | id=multi-select | label=Pennsylvania | 
    dropdown = self.driver.find_element(By.ID, "multi-select")
    dropdown.find_element(By.XPATH, "//option[. = 'Pennsylvania']").click()
    # 59 | addSelection | id=multi-select | label=California | 
    dropdown = self.driver.find_element(By.ID, "multi-select")
    dropdown.find_element(By.XPATH, "//option[. = 'California']").click()
    # 60 | click | id=printMe |  | 
    self.driver.find_element(By.ID, "printMe").click()
    # 61 | click | id=printMe |  | 
    self.driver.find_element(By.ID, "printMe").click()
    # 62 | click | id=printAll |  | 
    self.driver.find_element(By.ID, "printAll").click()
    # 63 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(3) > .tree-branch:nth-child(1) > a").click()
    # 64 | click | linkText=Ajax Form Submit |  | 
    self.driver.find_element(By.LINK_TEXT, "Ajax Form Submit").click()
    # 65 | click | id=title |  | 
    self.driver.find_element(By.ID, "title").click()
    # 66 | type | id=title | Selenium Test | 
    self.driver.find_element(By.ID, "title").send_keys("Selenium Test")
    # 67 | type | id=description | Test Tested again and again! | 
    self.driver.find_element(By.ID, "description").send_keys("Test Tested again and again!")
    # 68 | click | id=btn-submit |  | 
    self.driver.find_element(By.ID, "btn-submit").click()
    # 69 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(3) > .tree-branch:nth-child(1) > a").click()
    # 70 | click | linkText=JQuery Select dropdown |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Select dropdown").click()
    # 71 | click | css=.row > h3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row > h3").click()
    # 72 | click | css=.select2-search__field |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").click()
    # 73 | click | css=.panel:nth-child(2) > .panel-heading |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(2) > .panel-heading").click()
    # 74 | click | css=.select2-search__field |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").click()
    # 75 | click | css=.select2-selection--multiple > .select2-selection__rendered |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".select2-selection--multiple > .select2-selection__rendered").click()
    # 76 | click | css=.select2-selection--multiple > .select2-selection__rendered |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".select2-selection--multiple > .select2-selection__rendered").click()
    # 77 | click | id=select2-niq4-container |  | 
    self.driver.find_element(By.ID, "select2-niq4-container").click()
    # 78 | click | id=files |  | 
    self.driver.find_element(By.ID, "files").click()
    # 79 | select | id=files | label=Java | 
    dropdown = self.driver.find_element(By.ID, "files")
    dropdown.find_element(By.XPATH, "//option[. = 'Java']").click()
    # 80 | click | id=files |  | 
    self.driver.find_element(By.ID, "files").click()
    # 81 | click | css=.row:nth-child(5) .panel-body |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(5) .panel-body").click()
    # 82 | click | id=files |  | 
    self.driver.find_element(By.ID, "files").click()
    # 83 | click | id=files |  | 
    self.driver.find_element(By.ID, "files").click()
    # 84 | click | css=.text-center > .row |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
    # 85 | click | css=ul:nth-child(3) > .tree-branch:nth-child(1) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(3) > .tree-branch:nth-child(1) > a").click()
    # 86 | click | css=.tree-branch:nth-child(2) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(2) > a").click()
    # 87 | click | linkText=Bootstrap Date Picker |  | 
    self.driver.find_element(By.LINK_TEXT, "Bootstrap Date Picker").click()
    # 88 | click | css=.glyphicon-th |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-th").click()
    # 89 | click | css=tr:nth-child(2) > .day:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .day:nth-child(3)").click()
    # 90 | click | css=.glyphicon-th |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-th").click()
    # 91 | click | css=.datepicker-days .datepicker-switch |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .datepicker-switch").click()
    # 92 | click | css=.month:nth-child(6) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".month:nth-child(6)").click()
    # 93 | click | css=.datepicker-days .datepicker-switch |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .datepicker-switch").click()
    # 94 | click | css=.datepicker-months .datepicker-switch |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .datepicker-switch").click()
    # 95 | click | css=.year:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".year:nth-child(2)").click()
    # 96 | click | css=.month:nth-child(6) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".month:nth-child(6)").click()
    # 97 | click | css=tr:nth-child(3) > .day:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(4)").click()
    # 98 | runScript | window.scrollTo(0,500) |  | 
    self.driver.execute_script("window.scrollTo(0,500)")
    # 99 | click | css=#datepicker > .form-control:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#datepicker > .form-control:nth-child(1)").click()
    # 100 | click | css=tr:nth-child(3) > .day:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(4)").click()
    # 101 | click | css=.datepicker-days .datepicker-switch |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .datepicker-switch").click()
    # 102 | click | css=.datepicker-months .datepicker-switch |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .datepicker-switch").click()
    # 103 | click | css=.year:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".year:nth-child(1)").click()
    # 104 | click | css=.month:nth-child(6) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".month:nth-child(6)").click()
    # 105 | click | css=tr:nth-child(3) > .day:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(3)").click()
    # 106 | click | css=.row:nth-child(3) .panel-body |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .panel-body").click()
    # 107 | click | css=.form-control:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(3)").click()
    # 108 | click | css=tr:nth-child(2) > .range:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .range:nth-child(4)").click()
    # 109 | click | css=.text-center > .row |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
    # 110 | click | css=.tree-branch:nth-child(2) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(2) > a").click()
    # 111 | click | linkText=JQuery Date Picker |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Date Picker").click()
    # 112 | type | id=to | 10/10/2011 | 
    self.driver.find_element(By.ID, "to").send_keys("10/10/2011")
    # 113 | click | css=p:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    # 114 | click | id=to |  | 
    self.driver.find_element(By.ID, "to").click()
    # 115 | click | css=tr:nth-child(2) > td:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(3)").click()
    # 116 | click | id=from |  | 
    self.driver.find_element(By.ID, "from").click()
    # 117 | click | css=tr:nth-child(3) > td:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td:nth-child(4)").click()
    # 118 | click | css=.text-left |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-left").click()
    # 119 | click | css=.tree-branch:nth-child(2) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(2) > a").click()
    # 120 | click | css=.tree-branch:nth-child(3) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(3) > a").click()
    # 121 | click | linkText=Table Pagination |  | 
    self.driver.find_element(By.LINK_TEXT, "Table Pagination").click()
    # 122 | click | linkText=Table Pagination |  | 
    self.driver.find_element(By.LINK_TEXT, "Table Pagination").click()
    # 123 | click | linkText=2 |  | 
    self.driver.find_element(By.LINK_TEXT, "2").click()
    # 124 | click | linkText=3 |  | 
    self.driver.find_element(By.LINK_TEXT, "3").click()
    # 125 | click | css=tr:nth-child(11) > td:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(3)").click()
    # 126 | click | css=tr:nth-child(12) > td:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(12) > td:nth-child(3)").click()
    # 127 | click | css=tr:nth-child(12) > td:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(12) > td:nth-child(3)").click()
    # 128 | click | css=tr:nth-child(12) > td:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(12) > td:nth-child(3)").click()
    # 129 | click | css=.tree-branch:nth-child(3) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(3) > a").click()
    # 130 | click | linkText=Table Data Search |  | 
    self.driver.find_element(By.LINK_TEXT, "Table Data Search").click()
    # 131 | click | id=task-table-filter |  | 
    self.driver.find_element(By.ID, "task-table-filter").click()
    # 132 | type | id=task-table-filter | wire | 
    self.driver.find_element(By.ID, "task-table-filter").send_keys("wire")
    # 133 | click | css=.clickable > .glyphicon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".clickable > .glyphicon").click()
    # 134 | click | css=h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    # 135 | click | css=.text-center > .row |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
    # 136 | type | id=task-table-filter | joh | 
    self.driver.find_element(By.ID, "task-table-filter").send_keys("joh")
    # 137 | click | css=th:nth-child(1) > .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(1) > .form-control").click()
    # 138 | click | css=.btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 139 | click | css=th:nth-child(1) > .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(1) > .form-control").click()
    # 140 | click | css=.text-center > .row |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
    # 141 | click | css=.text-center > .row |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
    # 142 | type | css=th:nth-child(1) > .form-control | 2 | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(1) > .form-control").send_keys("2")
    # 143 | click | css=.tree-branch:nth-child(3) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(3) > a").click()
    # 144 | click | linkText=Table Filter |  | 
    self.driver.find_element(By.LINK_TEXT, "Table Filter").click()
    # 145 | click | css=.btn-success |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 146 | click | css=tr:nth-child(1) label |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) label").click()
    # 147 | click | css=.btn-warning |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-warning").click()
    # 148 | click | css=tr:nth-child(2) label |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) label").click()
    # 149 | click | css=tr:nth-child(5) label |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) label").click()
    # 150 | click | css=.btn-danger |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    # 151 | click | css=tr:nth-child(3) label |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) label").click()
    # 152 | click | css=.btn-default |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 153 | click | css=.selected:nth-child(3) label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".selected:nth-child(3) label").click()
    # 154 | click | css=.selected:nth-child(1) label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".selected:nth-child(1) label").click()
    # 155 | click | css=.tree-branch:nth-child(3) > .tree-indicator |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(3) > .tree-indicator").click()
    # 156 | click | linkText=Table Sort & Search |  | 
    self.driver.find_element(By.LINK_TEXT, "Table Sort & Search").click()
    # 157 | click | name=example_length |  | 
    self.driver.find_element(By.NAME, "example_length").click()
    # 158 | select | name=example_length | label=100 | 
    dropdown = self.driver.find_element(By.NAME, "example_length")
    dropdown.find_element(By.XPATH, "//option[. = '100']").click()
    # 159 | click | name=example_length |  | 
    self.driver.find_element(By.NAME, "example_length").click()
    # 160 | click | css=.sorting:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".sorting:nth-child(2)").click()
    # 161 | click | css=.tree-branch:nth-child(3) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(3) > a").click()
    # 162 | click | css=input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    # 163 | type | css=input | tokyo | 
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("tokyo")
    # 164 | sendKeys | css=input | ${KEY_ENTER} | 
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys(Keys.ENTER)
    # 165 | click | linkText=Table Data Download |  | 
    self.driver.find_element(By.LINK_TEXT, "Table Data Download").click()
    # 166 | click | css=th:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(3)").click()
    # 167 | click | css=tr:nth-child(7) > td:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(2)").click()
    # 168 | click | css=tr:nth-child(7) > td:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(2)").click()
    # 169 | doubleClick | css=tr:nth-child(7) > td:nth-child(2) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) > td:nth-child(2)")
    actions = ActionChains(driver)
    actions.double_click(element).perform()
    # 170 | click | linkText=Progress Bars & Sliders |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bars & Sliders").click()
    # 171 | click | css=.tree-branch:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(3)").click()
    # 172 | click | css=th:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(1)").click()
    # 173 | click | css=th:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(1)").click()
    # 174 | doubleClick | css=th:nth-child(1) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(1)")
    actions = ActionChains(driver)
    actions.double_click(element).perform()
    # 175 | click | css=th:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(2)").click()
    # 176 | click | css=th:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(3)").click()
    # 177 | click | linkText=JQuery Download Progress bars |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Download Progress bars").click()
    # 178 | click | id=downloadButton |  | 
    self.driver.find_element(By.ID, "downloadButton").click()
    # 179 | click | css=.ui-dialog-buttonset > button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > button").click()
    # 180 | click | linkText=Progress Bars & Sliders |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bars & Sliders").click()
    # 181 | click | linkText=JQuery Download Progress bars |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Download Progress bars").click()
    # 182 | click | id=downloadButton |  | 
    self.driver.find_element(By.ID, "downloadButton").click()
    # 183 | click | css=.ui-dialog-buttonset > button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > button").click()
    # 184 | click | css=.tree-branch:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(4)").click()
    # 185 | click | linkText=JQuery Download Progress bars |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Download Progress bars").click()
    # 186 | click | id=downloadButton |  | 
    self.driver.find_element(By.ID, "downloadButton").click()
    # 187 | click | css=.ui-dialog-buttonset > button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > button").click()
    # 188 | click | css=.tree-branch:nth-child(4) > .tree-indicator |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(4) > .tree-indicator").click()
    # 189 | click | linkText=Bootstrap Progress bar |  | 
    self.driver.find_element(By.LINK_TEXT, "Bootstrap Progress bar").click()
    # 190 | click | id=cricle-btn |  | 
    self.driver.find_element(By.ID, "cricle-btn").click()
    # 191 | click | id=cricle-btn |  | 
    self.driver.find_element(By.ID, "cricle-btn").click()
    # 192 | click | linkText=Progress Bars & Sliders |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bars & Sliders").click()
    # 193 | click | linkText=Drag & Drop Sliders |  | 
    self.driver.find_element(By.LINK_TEXT, "Drag & Drop Sliders").click()
    # 194 | type | name=range | 32 | 
    self.driver.find_element(By.NAME, "range").send_keys("32")
    # 195 | click | name=range |  | 
    self.driver.find_element(By.NAME, "range").click()
    # 196 | type | css=.range-primary > input | 79 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-primary > input").send_keys("79")
    # 197 | click | css=.range-primary > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-primary > input").click()
    # 198 | type | css=.range-success > input | 53 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-success > input").send_keys("53")
    # 199 | click | css=.range-success > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-success > input").click()
    # 200 | mouseDownAt | css=.range-success > input | 209.75,11 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".range-success > input")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 201 | mouseMoveAt | css=.range-success > input | 209.75,11 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".range-success > input")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 202 | mouseUpAt | css=.range-success > input | 209.75,11 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".range-success > input")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 203 | type | css=.range-success > input | 80 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-success > input").send_keys("80")
    # 204 | click | css=.range-success > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-success > input").click()
    # 205 | mouseDownAt | css=.range-info > input | 50.5,1 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".range-info > input")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 206 | mouseMoveAt | css=.range-info > input | 50.5,1 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".range-info > input")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 207 | mouseUpAt | css=.range-info > input | 50.5,1 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".range-info > input")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 208 | type | css=.range-info > input | 18 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-info > input").send_keys("18")
    # 209 | click | css=.range-info > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-info > input").click()
    # 210 | type | css=.range-danger > input | 79 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-danger > input").send_keys("79")
    # 211 | click | css=.range-danger > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-danger > input").click()
    # 212 | type | css=.range-danger > input | 1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-danger > input").send_keys("1")
    # 213 | click | css=.range-danger > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-danger > input").click()
    # 214 | type | css=.range-warning > input | 70 | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-warning > input").send_keys("70")
    # 215 | click | css=.range-warning > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-warning > input").click()
    # 216 | click | css=.tree-branch:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(4)").click()
    # 217 | click | linkText=JQuery Download Progress bars |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Download Progress bars").click()
    # 218 | click | id=downloadButton |  | 
    self.driver.find_element(By.ID, "downloadButton").click()
    # 219 | click | css=.ui-dialog-buttonset > button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > button").click()
    # 220 | click | linkText=Progress Bars & Sliders |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bars & Sliders").click()
    # 221 | click | linkText=JQuery Download Progress bars |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery Download Progress bars").click()
    # 222 | click | id=downloadButton |  | 
    self.driver.find_element(By.ID, "downloadButton").click()
    # 223 | click | css=.ui-dialog-buttonset > button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > button").click()
    # 224 | click | linkText=Progress Bars & Sliders |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bars & Sliders").click()
    # 225 | click | css=.tree-branch:nth-child(5) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5)").click()
    # 226 | click | linkText=Bootstrap Alerts |  | 
    self.driver.find_element(By.LINK_TEXT, "Bootstrap Alerts").click()
    # 227 | click | id=autoclosable-btn-success |  | 
    self.driver.find_element(By.ID, "autoclosable-btn-success").click()
    # 228 | click | id=normal-btn-success |  | 
    self.driver.find_element(By.ID, "normal-btn-success").click()
    # 229 | click | id=autoclosable-btn-warning |  | 
    self.driver.find_element(By.ID, "autoclosable-btn-warning").click()
    # 230 | click | id=normal-btn-warning |  | 
    self.driver.find_element(By.ID, "normal-btn-warning").click()
    # 231 | click | id=autoclosable-btn-danger |  | 
    self.driver.find_element(By.ID, "autoclosable-btn-danger").click()
    # 232 | click | id=normal-btn-danger |  | 
    self.driver.find_element(By.ID, "normal-btn-danger").click()
    # 233 | click | id=autoclosable-btn-info |  | 
    self.driver.find_element(By.ID, "autoclosable-btn-info").click()
    # 234 | click | id=normal-btn-info |  | 
    self.driver.find_element(By.ID, "normal-btn-info").click()
    # 235 | click | css=.footer |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".footer").click()
    # 236 | click | id=autoclosable-btn-info |  | 
    self.driver.find_element(By.ID, "autoclosable-btn-info").click()
    # 237 | click | css=.tree-branch:nth-child(5) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a").click()
    # 238 | click | linkText=Bootstrap Modals |  | 
    self.driver.find_element(By.LINK_TEXT, "Bootstrap Modals").click()
    # 239 | click | linkText=Launch modal |  | 
    self.driver.find_element(By.LINK_TEXT, "Launch modal").click()
    # 240 | click | linkText=Close |  | 
    self.driver.find_element(By.LINK_TEXT, "Close").click()
    # 241 | click | linkText=Launch modal |  | 
    self.driver.find_element(By.LINK_TEXT, "Launch modal").click()
    # 242 | mouseOver | linkText=Launch modal |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Launch modal")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 243 | mouseOut | linkText=Launch modal |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 244 | click | linkText=Save changes |  | 
    self.driver.find_element(By.LINK_TEXT, "Save changes").click()
    # 245 | click | css=.row:nth-child(3) .panel-body > .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .panel-body > .btn").click()
    # 246 | mouseOver | css=.row:nth-child(3) .panel-body > .btn |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .panel-body > .btn")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 247 | mouseOut | css=.row:nth-child(3) .panel-body > .btn |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 248 | click | css=.btn:nth-child(7) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(7)").click()
    # 249 | mouseOver | css=.btn:nth-child(7) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(7)")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 250 | mouseOut | css=.btn:nth-child(7) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 251 | click | css=.modal-footer:nth-child(6) > .btn:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer:nth-child(6) > .btn:nth-child(1)").click()
    # 252 | click | linkText=Close |  | 
    self.driver.find_element(By.LINK_TEXT, "Close").click()
    # 253 | click | css=.tree-branch:nth-child(5) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a").click()
    # 254 | click | linkText=Window Popup Modal |  | 
    self.driver.find_element(By.LINK_TEXT, "Window Popup Modal").click()
    # 255 | click | linkText=Follow On Twitter |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 256 | storeWindowHandle | root |  | 
    self.driver.find_element(By.LINK_TEXT, "Follow On Twitter").click()
    # 257 | selectWindow | handle=${win8669} |  | 
    self.vars["win8669"] = self.wait_for_window(2000)
    # 258 | close |  |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 259 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["win8669"])
    # 260 | mouseOver | linkText=Like us On Facebook |  | 
    self.driver.close()
    # 261 | click | linkText=Like us On Facebook |  | 
    self.driver.switch_to.window(self.vars["root"])
    # 262 | mouseOut | linkText=Like us On Facebook |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Like us On Facebook")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 263 | selectWindow | handle=${win6493} |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 264 | close |  |  | 
    self.driver.find_element(By.LINK_TEXT, "Like us On Facebook").click()
    # 265 | selectWindow | handle=${root} |  | 
    self.vars["win6493"] = self.wait_for_window(2000)
    # 266 | mouseDownAt | linkText=Follow Twitter & Facebook | 159.75,14 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 267 | mouseMoveAt | linkText=Follow Twitter & Facebook | 159.75,14 | 
    self.driver.switch_to.window(self.vars["win6493"])
    # 268 | mouseUpAt | linkText=Follow Twitter & Facebook | 159.75,14 | 
    self.driver.close()
    # 269 | click | linkText=Follow Twitter & Facebook |  | 
    self.driver.switch_to.window(self.vars["root"])
    # 270 | selectWindow | handle=${win5817} |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Follow Twitter & Facebook")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 271 | verifyTitle | Selenium Easy (@seleniumeasy) on Twitter |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Follow Twitter & Facebook")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 272 | close |  |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Follow Twitter & Facebook")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 273 | selectWindow | handle=${root} |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 274 | mouseOver | linkText=Follow Twitter & Facebook |  | 
    self.driver.find_element(By.LINK_TEXT, "Follow Twitter & Facebook").click()
    # 275 | mouseOut | linkText=Follow Twitter & Facebook |  | 
    self.vars["win5817"] = self.wait_for_window(2000)
    # 276 | mouseDownAt | id=followall | 64.75,20 | 
    self.driver.switch_to.window(self.vars["win5817"])
    # 277 | mouseMoveAt | id=followall | 64.75,20 | 
    assert self.driver.title == "Selenium Easy (@seleniumeasy) on Twitter"
    # 278 | mouseUpAt | id=followall | 64.75,20 | 
    self.driver.close()
    # 279 | click | id=followall |  | 
    self.driver.switch_to.window(self.vars["root"])
    # 280 | selectWindow | handle=${win4983} |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Follow Twitter & Facebook")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 281 | close |  |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 282 | selectWindow | handle=${root} |  | 
    element = self.driver.find_element(By.ID, "followall")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 283 | mouseDownAt | css=.tree-branch:nth-child(5) > a | 57.125,5 | 
    element = self.driver.find_element(By.ID, "followall")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 284 | mouseMoveAt | css=.tree-branch:nth-child(5) > a | 57.125,5 | 
    element = self.driver.find_element(By.ID, "followall")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 285 | mouseUpAt | css=.tree-branch:nth-child(5) > a | 57.125,5 | 
    self.vars["window_handles"] = self.driver.window_handles
    # 286 | click | css=.tree-branch:nth-child(5) > a |  | 
    self.driver.find_element(By.ID, "followall").click()
    # 287 | mouseDownAt | css=.tree-branch:nth-child(6) > a | 27.125,7 | 
    self.vars["win4983"] = self.wait_for_window(2000)
    # 288 | mouseMoveAt | css=.tree-branch:nth-child(6) > a | 27.125,7 | 
    self.driver.switch_to.window(self.vars["win4983"])
    # 289 | mouseUpAt | css=.tree-branch:nth-child(6) > a | 27.125,7 | 
    self.driver.close()
    # 290 | click | css=.tree-branch:nth-child(6) > a |  | 
    self.driver.switch_to.window(self.vars["root"])
    # 291 | mouseDownAt | linkText=Progress Bar Modal | 96,4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 292 | mouseMoveAt | linkText=Progress Bar Modal | 96,4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 293 | mouseUpAt | linkText=Progress Bar Modal | 96,4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 294 | click | linkText=Progress Bar Modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a").click()
    # 295 | click | css=.btn-primary |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 296 | click | css=.btn-success |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 297 | click | css=.btn-warning |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 298 | mouseOver | css=.btn-warning |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a").click()
    # 299 | mouseOut | css=.btn-warning |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Progress Bar Modal")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 300 | click | css=.btn-success |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Progress Bar Modal")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 301 | click | css=.btn-warning |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Progress Bar Modal")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    # 302 | mouseOver | css=.btn-warning |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bar Modal").click()
    # 303 | mouseOut | css=.btn-warning |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    # 304 | click | css=.modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 305 | click | css=.modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-warning").click()
    # 306 | click | css=.tree-branch:nth-child(5) > a |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-warning")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 307 | click | linkText=File Download |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 308 | click | id=textbox |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 309 | type | id=textbox | Testing Selenium | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-warning").click()
    # 310 | click | id=create |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-warning")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 311 | click | id=link-to-download |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 312 | click | css=.tree-branch:nth-child(5) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal").click()
    # 313 | click | linkText=Javascript Alerts |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal").click()
    # 314 | click | css=.panel:nth-child(4) .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a").click()
    # 315 | assertAlert | I am an alert box! |  | 
    self.driver.find_element(By.LINK_TEXT, "File Download").click()
    # 316 | chooseOkOnNextConfirmation |  |  | 
    self.driver.find_element(By.ID, "textbox").click()
    # 317 | click | css=.panel:nth-child(5) .btn |  | 
    self.driver.find_element(By.ID, "textbox").send_keys("Testing Selenium")
    # 318 | assertConfirmation | Press a button! |  | 
    self.driver.find_element(By.ID, "create").click()
    # 319 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    self.driver.find_element(By.ID, "link-to-download").click()
    # 320 | chooseCancelOnNextConfirmation |  |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a").click()
    # 321 | click | css=.panel:nth-child(5) .btn |  | 
    self.driver.find_element(By.LINK_TEXT, "Javascript Alerts").click()
    # 322 | assertConfirmation | Press a button! |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(4) .btn").click()
    # 323 | webdriverChooseCancelOnVisibleConfirmation |  |  | 
    assert self.driver.switch_to.alert.text == "I am an alert box!"
    # 324 | answerOnNextPrompt | Hello World! |  | 
    # 325 | click | css=.panel:nth-child(6) .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(5) .btn").click()
    # 326 | assertPrompt | Please enter your name |  | 
    assert self.driver.switch_to.alert.text == "Press a button!"
    # 327 | webdriverAnswerOnVisiblePrompt | Hello World! |  | 
    self.driver.switch_to.alert.accept()
    # 328 | answerOnNextPrompt | It's OK |  | 
    # 329 | click | css=.panel:nth-child(6) .btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(5) .btn").click()
    # 330 | assertPrompt | Please enter your name |  | 
    assert self.driver.switch_to.alert.text == "Press a button!"
    # 331 | webdriverAnswerOnVisiblePrompt | It's OK |  | 
    self.driver.switch_to.alert.dismiss()
    # 332 | click | css=.tree-branch:nth-child(5) > a |  | 
    # 333 | click | linkText=Progress Bar Modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(6) .btn").click()
    # 334 | click | css=.tree-branch:nth-child(6) > a |  | 
    assert self.driver.switch_to.alert.text == "Please enter your name"
    # 335 | click | linkText=Bootstrap List Box |  | 
    alert = self.driver.switch_to.alert
    alert.send_keys("Hello World!")
    alert.accept()
    # 336 | click | css=.text-right .list-group-item:nth-child(1) |  | 
    # 337 | click | css=.col-md-2:nth-child(2) .glyphicon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(6) .btn").click()
    # 338 | click | css=.move-right |  | 
    assert self.driver.switch_to.alert.text == "Please enter your name"
    # 339 | click | css=.list-group-item:nth-child(3) |  | 
    alert = self.driver.switch_to.alert
    alert.send_keys("It\'s OK")
    alert.accept()
    # 340 | click | css=.glyphicon-chevron-left |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(5) > a").click()
    # 341 | click | css=.move-right > .glyphicon |  | 
    self.driver.find_element(By.LINK_TEXT, "Progress Bar Modal").click()
    # 342 | click | css=.list-group-item:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a").click()
    # 343 | click | css=.list-group-item:nth-child(5) |  | 
    self.driver.find_element(By.LINK_TEXT, "Bootstrap List Box").click()
    # 344 | click | css=.list-group-item:nth-child(6) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-right .list-group-item:nth-child(1)").click()
    # 345 | click | css=.list-group-item:nth-child(8) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-2:nth-child(2) .glyphicon").click()
    # 346 | click | css=.list-group-item:nth-child(9) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".move-right").click()
    # 347 | click | css=.move-left |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3)").click()
    # 348 | click | css=.form-control:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-chevron-left").click()
    # 349 | click | css=.form-control:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".move-right > .glyphicon").click()
    # 350 | click | css=.form-control:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(1)").click()
    # 351 | type | css=.form-control:nth-child(1) | leo | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(5)").click()
    # 352 | click | css=.list-group-item:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(6)").click()
    # 353 | click | css=.list-group-item:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(8)").click()
    # 354 | click | css=.list-group-item:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(9)").click()
    # 355 | doubleClick | css=.list-group-item:nth-child(4) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".move-left").click()
    # 356 | click | css=.input-group-addon:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    # 357 | click | css=.tree-branch:nth-child(6) > .tree-indicator |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    # 358 | click | linkText=JQuery List Box |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    # 359 | addSelection | css=.pickData | label=Manuela | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").send_keys("leo")
    # 360 | addSelection | css=.pickData | label=Laura | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(4)").click()
    # 361 | addSelection | css=.pickData | label=Luiza | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(4)").click()
    # 362 | addSelection | css=.pickData | label=Valentina | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(4)").click()
    # 363 | addSelection | css=.pickData | label=Giovanna | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(4)")
    actions = ActionChains(driver)
    actions.double_click(element).perform()
    # 364 | click | css=.pAdd |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".input-group-addon:nth-child(2)").click()
    # 365 | addSelection | css=.pickListResult | label=Valentina | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > .tree-indicator").click()
    # 366 | click | css=.pRemove |  | 
    self.driver.find_element(By.LINK_TEXT, "JQuery List Box").click()
    # 367 | addSelection | css=.pickData | label=Maria Luiza | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickData")
    dropdown.find_element(By.XPATH, "//option[. = 'Manuela']").click()
    # 368 | click | css=.pAdd |  | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickData")
    dropdown.find_element(By.XPATH, "//option[. = 'Laura']").click()
    # 369 | click | css=.tree-branch:nth-child(6) > a |  | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickData")
    dropdown.find_element(By.XPATH, "//option[. = 'Luiza']").click()
    # 370 | click | linkText=Data List Filter |  | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickData")
    dropdown.find_element(By.XPATH, "//option[. = 'Valentina']").click()
    # 371 | click | css=.items:nth-child(1) .glyphicon |  | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickData")
    dropdown.find_element(By.XPATH, "//option[. = 'Giovanna']").click()
    # 372 | click | id=input-search |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".pAdd").click()
    # 373 | type | id=input-search | Tree | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickListResult")
    dropdown.find_element(By.XPATH, "//option[. = 'Valentina']").click()
    # 374 | click | css=.items:nth-child(2) span:nth-child(5) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".pRemove").click()
    # 375 | click | css=.text-center > .row |  | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".pickData")
    dropdown.find_element(By.XPATH, "//option[. = 'Maria Luiza']").click()
    # 376 | type | id=input-search | Hoy | 
    self.driver.find_element(By.CSS_SELECTOR, ".pAdd").click()
    # 377 | click | css=.tree-branch:nth-child(6) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a").click()
    # 378 | click | css=.tree-branch:nth-child(7) > a |  | 
    self.driver.find_element(By.LINK_TEXT, "Data List Filter").click()
    # 379 | click | linkText=Drag and Drop |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".items:nth-child(1) .glyphicon").click()
    # 380 | dragAndDropToObject | css=#todrag > span:nth-child(3) | id=mydropzone | 
    self.driver.find_element(By.ID, "input-search").click()
    # 381 | dragAndDropToObject | css=#todrag > span:nth-child(2) | id=mydropzone | 
    self.driver.find_element(By.ID, "input-search").send_keys("Tree")
    # 382 | click | css=#droppedlist > span:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".items:nth-child(2) span:nth-child(5)").click()
    # 383 | dragAndDropToObject | css=#todrag > span:nth-child(3) | id=mydropzone | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
    # 384 | dragAndDropToObject | css=#todrag > span | id=mydropzone | 
    self.driver.find_element(By.ID, "input-search").send_keys("Hoy")
    # 385 | click | css=.tree-branch:nth-child(7) > a |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a").click()
    # 386 | click | linkText=Dynamic Data Loading |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(7) > a").click()
    # 387 | click | id=save |  | 
    self.driver.find_element(By.LINK_TEXT, "Drag and Drop").click()
    # 388 | click | css=.panel:nth-child(3) > .panel-body |  | 
    dragged = self.driver.find_element(By.CSS_SELECTOR, "#todrag > span:nth-child(3)")
    dropped = self.driver.find_element(By.ID, "mydropzone")
    actions = ActionChains(driver)
    actions.drag_and_drop(dragged, dropped).perform()
    # 389 | click | id=save |  | 
    dragged = self.driver.find_element(By.CSS_SELECTOR, "#todrag > span:nth-child(2)")
    dropped = self.driver.find_element(By.ID, "mydropzone")
    actions = ActionChains(driver)
    actions.drag_and_drop(dragged, dropped).perform()
    # 390 | click | id=save |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#droppedlist > span:nth-child(1)").click()
    # 391 | click | id=save |  | 
    dragged = self.driver.find_element(By.CSS_SELECTOR, "#todrag > span:nth-child(3)")
    dropped = self.driver.find_element(By.ID, "mydropzone")
    actions = ActionChains(driver)
    actions.drag_and_drop(dragged, dropped).perform()
    # 392 | click | id=save |  | 
    dragged = self.driver.find_element(By.CSS_SELECTOR, "#todrag > span")
    dropped = self.driver.find_element(By.ID, "mydropzone")
    actions = ActionChains(driver)
    actions.drag_and_drop(dragged, dropped).perform()
    # 393 | click | id=save |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(7) > a").click()
    # 394 | click | id=save |  | 
    self.driver.find_element(By.LINK_TEXT, "Dynamic Data Loading").click()
    # 395 | click | id=save |  | 
    self.driver.find_element(By.ID, "save").click()
    # 396 | click | id=save |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(3) > .panel-body").click()
    # 397 | click | id=save |  | 
    self.driver.find_element(By.ID, "save").click()
    # 398 | click | id=save |  | 
    self.driver.find_element(By.ID, "save").click()
    # 399 | mouseOver | id=save |  | 
    self.driver.find_element(By.ID, "save").click()
    # 400 | click | id=save |  | 
    self.driver.find_element(By.ID, "save").click()
    # 401 | mouseOut | id=save |  | 
    self.driver.find_element(By.ID, "save").click()
    # 402 | mouseOver | css=.tree-branch:nth-child(6) > a |  | 
    self.driver.find_element(By.ID, "save").click()
    # 403 | mouseOut | css=.tree-branch:nth-child(6) > a |  | 
    self.driver.find_element(By.ID, "save").click()
    # 404 | click | css=.tree-branch:nth-child(7) > a |  | 
    self.driver.find_element(By.ID, "save").click()
    # 405 | click | linkText=Dynamic Data Loading |  | 
    self.driver.find_element(By.ID, "save").click()
    # 406 | click | css=.tree-branch:nth-child(7) > a |  | 
    self.driver.find_element(By.ID, "save").click()
    # 407 | click | linkText=Charts Demo |  | 
    element = self.driver.find_element(By.ID, "save")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 408 | click | id=myBarChart |  | 
    self.driver.find_element(By.ID, "save").click()
    # 409 | click | css=.btn:nth-child(1) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 410 | click | css=.video > h2 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(6) > a")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 411 | click | css=.btn:nth-child(2) |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 412 | assertText | css=.btn:nth-child(2) | PICTURES | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(7) > a").click()
    # 413 | verifyTitle | Selenium Easy - Charts Mouse Hover |  | 
    self.driver.find_element(By.LINK_TEXT, "Dynamic Data Loading").click()
    # 414 | click | css=.tree-branch:nth-child(7) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(7) > a").click()
    # 415 | click | linkText=Others |  | 
    self.driver.find_element(By.LINK_TEXT, "Charts Demo").click()
    # 416 | click | linkText=List Box |  | 
    self.driver.find_element(By.ID, "myBarChart").click()
    # 417 | click | linkText=JQuery List Box |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    # 418 | click | linkText=Input Forms |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".video > h2").click()
    # 419 | click | id=site-slogan |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 420 | close |  |  | 
    assert self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").text == "PICTURES"
    assert self.driver.title == "Selenium Easy - Charts Mouse Hover"
    self.driver.find_element(By.CSS_SELECTOR, ".tree-branch:nth-child(7)").click()
    self.driver.find_element(By.LINK_TEXT, "Others").click()
    self.driver.find_element(By.LINK_TEXT, "List Box").click()
    self.driver.find_element(By.LINK_TEXT, "JQuery List Box").click()
    self.driver.find_element(By.LINK_TEXT, "Input Forms").click()
    self.driver.find_element(By.ID, "site-slogan").click()
    self.driver.close()
  
